export const GARAGE = [
	{
		name: "Abider",
		type: "Civilian",
		fuelCapacity: 49,
		efficiency: 3.28,
		imgUrl: "/img/abider.png",
	},
	{
		name: "Afterburn",
		type: "Civilian",
		fuelCapacity: 16,
		efficiency: 3.16,
		imgUrl: "/img/afterburn.png",
	},
	{
		name: "Boson",
		type: "Electric",
		battery: 16,
		batteryCharge: 2.16,
		imgUrl: "/img/boson.png",
	},
	{
		name: "Exstatic",
		type: "Electric",
		battery: 16,
		batteryCharge: 2.16,
		imgUrl: "/img/exstatic.png",
	},
	{
		name: "Blaze",
		type: "Civilian",
		fuelCapacity: 46.5,
		efficiency: 1.8,
		imgUrl: "/img/blaze.png",
	},
	{
		name: "GX Spider",
		type: "Civilian",
		fuelCapacity: 18,
		efficiency: 3.16,
		imgUrl: "/img/gxspider.png",
	},
	{
		name: "Flare",
		type: "Electric",
		battery: 16,
		batteryCharge: 1.16,

		imgUrl: "/img/flare.png",
	},
	{
		name: "Landscape",
		type: "Civilian",
		fuelCapacity: 46.5,
		efficiency: 3,
		imgUrl: "/img/landscape.png",
	},
	{
		name: "Path Watcher",
		type: "Civilian",
		fuelCapacity: 49,
		efficiency: 2.78,
		imgUrl: "/img/pathwatcher.png",
	},
	{
		name: "Scenery",
		type: "Civilian",
		fuelCapacity: 46.5,
		efficiency: 2.8,
		imgUrl: "/img/scenery.png",
	},
	{
		name: "VectorBlade",
		type: "Electric",
		battery: 12,
		batteryCharge: 2,
		imgUrl: "/img/vectorblade.png",
	},
	{
		name: "Road CM",
		type: "Motorbike",
		battery: 18,
		batteryCharge: 2.5,
		imgUrl: "/img/roadcm.png",
	},
	{
		name: "Firespin",
		type: "Electric",
		battery: 18,
		batteryCharge: 2.5,
		imgUrl: "/img/firespin.png",
	},
	{
		name: "Terminator Motorbike",
		type: "Motorbike",
		fuelCapacity: 12,
		efficiency: 2,
		imgUrl: "/img/terminatorMotorbike.png",
	},
	{
		name: "IC-8 Incursion",
		type: "APC",
		fuelCapacity: 33,
		efficiency: 4,
		imgUrl: "/img/ic-8Incursion.png",
	},
	{
		name: "LC-4 Coercion",
		fuelCapacity: 50,
		efficiency: 3,
		type: "Heavy",
		imgUrl: "/img/lc-4Coercion.png",
	},
	{
		name: "MC-1 Restraint",
		type: "Heavy",
		fuelCapacity: 40,
		efficiency: 3,
		imgUrl: "/img/mc-1Restraint.png",
	},
	{
		name: "Exoshell",
		type: "Heavy",
		fuelCapacity: 40,
		efficiency: 3.8,
		imgUrl: "/img/exoshell.png",
	},
	{
		name: "MC-2 Pressure",
		type: "Heavy",
		fuelCapacity: 40,
		efficiency: 2.8,
		imgUrl: "/img/mc-2Pressure.png",
	},
	{
		name: "Path Keeper",
		type: "Military",
		fuelCapacity: 30,
		efficiency: 2.8,
		imgUrl: "/img/pathkeeper.png",
	},
	{
		name: "CV-1 Desert",
		type: "Military",
		fuelCapacity: 27,
		efficiency: 2,
		imgUrl: "/img/cv-1Desert.png",
	},
	{
		name: "RT-5 Shepherd",
		type: "Heavy",
		fuelCapacity: 40,
		efficiency: 3.8,
		imgUrl: "/img/rt-5Shepard.png",
	},
	{
		name: "Starfield X4",
		type: "Heavy",
		fuelCapacity: 38,
		efficiency: 2.2,
		imgUrl: "/img/starfieldx4.png",
	},
	{
		name: "Resistance Car",
		type: "Military",
		fuelCapacity: 12,
		efficiency: 2,
		imgUrl: "/img/resistance.png",
	},
	{
		name: "Warden",
		type: "Heavy",
		fuelCapacity: 38,
		efficiency: 2,
		imgUrl: "/img/warden.png",
	},
	{
		name: "Trail EX",
		type: "Electric",
		battery: 18,
		batteryCharge: 2.5,
		imgUrl: "/img/trailex.png",
	},
	{
		name: "Trail TX",
		type: "Motorbike",
		fuelCapacity: 12,
		efficiency: 2,
		imgUrl: "/img/trailtx.png",
	},
	{
		name: "Deinos",
		timer: 600,
		type: "Aircraft",
		imgUrl: "/img/deinos.png",
	},
	{
		name: "Gyps",
		timer: 720,
		type: "Aircraft",
		imgUrl: "/img/gyps.png",
	},
	{
		name: "Opheis",
		timer: 680,
		type: "Aircraft",
		imgUrl: "/img/opheis.png",
	},
	{
		name: "Overseer",
		timer: 900,
		type: "Aircraft",
		imgUrl: "/img/oversteer.png",
	},
	{
		name: "Blacklist helicopter",
		timer: 790,
		type: "Aircraft",
		imgUrl: "/img/blacklist.png",
	},
	{
		name: "RQ-9 Reaper",
		timer: 900,
		type: "UAV",
		imgUrl: "/img/Drone.png",
	},
	{
		name: "RQ-7 Shadow",
		timer: 900,
		type: "UAV",
		imgUrl: "/img/rq-7.png",
	},
	{
		name: "AC-130 Gunship",
		timer: 900,
		type: "Aircraft",
		imgUrl: "/img/ac-130.png",
	},
	{
		name: "A-10 Warthog",
		timer: 900,
		type: "Aircraft",
		imgUrl: "/img/a-10.png",
	},
	{
		name: "JLTV",
		type: "Heavy",
		fuelCapacity: 38,
		efficiency: 2.2,
		imgUrl: "/img/JLTV.png",
	},
	{
		name: "UH-60 Blackhawk",
		timer: 720,
		type: "Aircraft",
		imgUrl: "/img/Blackhawk.png",
	},
];
