// All vehicles use maxTime (minutes of operational time at full fuel)
// and wearRate (% wear added per minute of use).
// Condition thresholds: Optimal <25%, Operational <50%, Compromised <75%, Critical 75%+
export const GARAGE = [
	{
		name: "Abider",
		type: "Civilian",
		maxTime: 9,
		wearRate: 4,
		imgUrl: "/img/abider.png",
	},
	{
		name: "Afterburn",
		type: "Civilian",
		maxTime: 6,
		wearRate: 5,
		imgUrl: "/img/afterburn.png",
	},
	{
		name: "Boson",
		type: "Electric",
		maxTime: 7,
		wearRate: 4,
		imgUrl: "/img/boson.png",
	},
	{
		name: "Exstatic",
		type: "Electric",
		maxTime: 7,
		wearRate: 4,
		imgUrl: "/img/exstatic.png",
	},
	{
		name: "Blaze",
		type: "Civilian",
		maxTime: 8,
		wearRate: 4,
		imgUrl: "/img/blaze.png",
	},
	{
		name: "GX Spider",
		type: "Civilian",
		maxTime: 6,
		wearRate: 5,
		imgUrl: "/img/gxspider.png",
	},
	{
		name: "Flare",
		type: "Electric",
		maxTime: 9,
		wearRate: 4,
		imgUrl: "/img/flare.png",
	},
	{
		name: "Landscape",
		type: "Civilian",
		maxTime: 8,
		wearRate: 4,
		imgUrl: "/img/landscape.png",
	},
	{
		name: "Path Watcher",
		type: "Civilian",
		maxTime: 9,
		wearRate: 4,
		imgUrl: "/img/pathwatcher.png",
	},
	{
		name: "Scenery",
		type: "Civilian",
		maxTime: 8,
		wearRate: 4,
		imgUrl: "/img/scenery.png",
	},
	{
		name: "VectorBlade",
		type: "Electric",
		maxTime: 6,
		wearRate: 4,
		imgUrl: "/img/vectorblade.png",
	},
	{
		name: "Road CM",
		type: "Motorbike",
		maxTime: 8,
		wearRate: 6,
		imgUrl: "/img/roadcm.png",
	},
	{
		name: "Firespin",
		type: "Electric",
		maxTime: 8,
		wearRate: 4,
		imgUrl: "/img/firespin.png",
	},
	{
		name: "Terminator Motorbike",
		type: "Motorbike",
		maxTime: 6,
		wearRate: 6,
		imgUrl: "/img/terminatorMotorbike.png",
	},
	{
		name: "IC-8 Incursion",
		type: "APC",
		maxTime: 6,
		wearRate: 7,
		imgUrl: "/img/ic-8Incursion.png",
	},
	{
		name: "LC-4 Coercion",
		type: "Heavy",
		maxTime: 8,
		wearRate: 6,
		imgUrl: "/img/lc-4Coercion.png",
	},
	{
		name: "MC-1 Restraint",
		type: "Heavy",
		maxTime: 8,
		wearRate: 6,
		imgUrl: "/img/mc-1Restraint.png",
	},
	{
		name: "Exoshell",
		type: "Heavy",
		maxTime: 7,
		wearRate: 7,
		imgUrl: "/img/exoshell.png",
	},
	{
		name: "MC-2 Pressure",
		type: "Heavy",
		maxTime: 8,
		wearRate: 6,
		imgUrl: "/img/mc-2Pressure.png",
	},
	{
		name: "Path Keeper",
		type: "Military",
		maxTime: 8,
		wearRate: 5,
		imgUrl: "/img/pathkeeper.png",
	},
	{
		name: "CV-1 Desert",
		type: "Military",
		maxTime: 8,
		wearRate: 5,
		imgUrl: "/img/cv-1Desert.png",
	},
	{
		name: "RT-5 Shepherd",
		type: "Heavy",
		maxTime: 7,
		wearRate: 7,
		imgUrl: "/img/rt-5Shepard.png",
	},
	{
		name: "Starfield X4",
		type: "Heavy",
		maxTime: 9,
		wearRate: 6,
		imgUrl: "/img/starfieldx4.png",
	},
	{
		name: "Resistance Car",
		type: "Military",
		maxTime: 6,
		wearRate: 5,
		imgUrl: "/img/resistance.png",
	},
	{
		name: "Warden",
		type: "Heavy",
		maxTime: 9,
		wearRate: 5,
		imgUrl: "/img/warden.png",
	},
	{
		name: "Trail EX",
		type: "Electric",
		maxTime: 8,
		wearRate: 4,
		imgUrl: "/img/trailex.png",
	},
	{
		name: "Trail TX",
		type: "Motorbike",
		maxTime: 6,
		wearRate: 6,
		imgUrl: "/img/trailtx.png",
	},
	{
		name: "Deinos",
		type: "Aircraft",
		maxTime: 10,
		wearRate: 5,
		imgUrl: "/img/deinos.png",
	},
	{
		name: "Gyps",
		type: "Aircraft",
		maxTime: 10,
		wearRate: 5,
		imgUrl: "/img/gyps.png",
	},
	{
		name: "Opheis",
		type: "Aircraft",
		maxTime: 10,
		wearRate: 5,
		imgUrl: "/img/opheis.png",
	},
	{
		name: "Overseer",
		type: "Aircraft",
		maxTime: 10,
		wearRate: 5,
		imgUrl: "/img/oversteer.png",
	},
	{
		name: "Blacklist helicopter",
		type: "Aircraft",
		maxTime: 10,
		wearRate: 5,
		imgUrl: "/img/blacklist.png",
	},
	{
		name: "RQ-9 Reaper",
		type: "UAV",
		maxTime: 10,
		wearRate: 3,
		imgUrl: "/img/Drone.png",
	},
	{
		name: "RQ-7 Shadow",
		type: "UAV",
		maxTime: 10,
		wearRate: 3,
		imgUrl: "/img/rq-7.png",
	},
	{
		name: "AC-130 Gunship",
		type: "Aircraft",
		maxTime: 10,
		wearRate: 4,
		imgUrl: "/img/ac-130.png",
	},
	{
		name: "A-10 Warthog",
		type: "Aircraft",
		maxTime: 10,
		wearRate: 5,
		imgUrl: "/img/a-10.png",
	},
	{
		name: "JLTV",
		type: "Heavy",
		maxTime: 8,
		wearRate: 6,
		imgUrl: "/img/JLTV.png",
	},
	{
		name: "UH-60 Blackhawk",
		type: "Aircraft",
		maxTime: 10,
		wearRate: 5,
		imgUrl: "/img/Blackhawk.png",
	},
];
