export const ITEMS = {
	C4: "/icons/C4.svg",
	Flashbang: "/icons/Flashbang.svg",
	Blowtorch: "/icons/BreachingTorch.svg",
	"Gas Mask": "/icons/GasMask.svg",
	"Gas Grenade": "/icons/Gas.svg",
	"Strike Designator": "/icons/StrikeDesignator.svg",
	"Intel Grenade": "/icons/SensorGrenade.svg",
	"EMP Grenade": "/icons/EMPGrenade.svg",
	"Sonar Goggles": "/icons/SensorGoggles.svg",
	"Shock Pistol": "/icons/ShockPistol.svg",
	"Sync Shot Drone": "/icons/SyncShotDrone.svg",
	"Frag Grenade": "/icons/FragGrenade.svg",
	"Grenade Launcher": "/icons/GrenadeLauncher.svg",
	"Rocket Launcher": "/icons/RocketLauncher.svg",
	Mine: "/icons/Mine.svg",
	"Sensor Launcher": "/icons/SensorLauncher.svg",
	"Armaros Drone": "/icons/ArmarosDrone.svg",
	Bandages: "/icons/Bandages.svg",
	"Syringe MK2": "/icons/SyringeMK2.svg",
	"Syringe ": "/icons/SyringeMK2.svg",
	Binoculars: "/icons/Binoculars.svg",
	"Recon Drone": "/icons/ReconDrone.svg",
	"Attack Helicopter": "/icons/AttackHelicopter.svg",
	"Transport Helicopter": "/icons/TransportHelicopter.svg",
	"Cloak Spray": "/icons/CloakSpray.svg",
	"Battle Drone": "/icons/BattleDrone.svg",
	"Shot Gun": "/icons/STG.svg",
};

// Maps item names to their restriction key in PROVINCE_RESTRICTIONS.
// Add entries here when adding new items. Leave unmapped items unrestricted.
export const ITEM_RESTRICTION_KEYS = {
	"Recon Drone":          "reconDrone",
	"Sync Shot Drone":      "syncDrone",
	"Armaros Drone":        "uplinkProtocol",
	"Battle Drone":         "combatDrone",
	"Attack Helicopter":    "aviation",
	"Transport Helicopter": "aviation",
	"Strike Designator":    "isrDrone",
	"Intel Grenade":        "intelGrenades",
	"Sonar Goggles":        "sonarVision",
	Binoculars:             "lrOptics",
};
