export const ITEMS = {
	C4: "/icons/C4.svg",
	Flashbang: "/icons/Flashbang.svg",
	Blowtorch: "/icons/BreachingTorch.svg",
	"Gas Mask": "/icons/GasMask.svg",
	"Gas Grenade": "/icons/Gas.svg",
	"Strike Designator": "/icons/StrikeDesignator.svg",
	"Intel Grenade": "/icons/SensorGrenade.svg",
	"EMP Grenade": "/icons/EMPGrenade.svg",
	"Sonar Goggles": "/icons/SensorGoggles.svg",
	"Shock Pistol": "/icons/ShockPistol.svg",
	"Sync Shot Drone": "/icons/SyncShotDrone.svg",
	"Frag Grenade": "/icons/FragGrenade.svg",
	"Rocket Launcher": "/icons/RocketLauncher.svg",
	Mine: "/icons/Mine.svg",
	"Sensor Launcher": "/icons/SensorLauncher.svg",
	"Uplink Protocol": "/icons/ArmarosDrone.svg",
	Bandages: "/icons/Bandages.svg",
	Medkit: "/icons/Medkit.svg",
	"Supply Drone": "/icons/SupplyDrone.svg",
	"Syringe ": "/icons/SyringeMK2.svg",
	Binoculars: "/icons/Binoculars.svg",
	"Recon Drone": "/icons/ReconDrone.svg",
	"Cloak Spray": "/icons/CloakSpray.svg",
	"Battle Drone": "/icons/BattleDrone.svg",
};

// Maps item names to their restriction key in PROVINCE_RESTRICTIONS.
// Add entries here when adding new items. Leave unmapped items unrestricted.
export const ITEM_RESTRICTION_KEYS = {
	"Recon Drone": "reconDrone",
	"Sync Shot Drone": "syncDrone",
	"Supply Drone": "supplyDrone",
	"Uplink Protocol": "uplinkProtocol",
	"Battle Drone": "combatDrone",
	"Strike Designator": "aviation",
	"Intel Grenade": "intelGrenades",
	"Sensor Launcher": "intelGrenades",
	"Sonar Goggles": "sonarVision",
	Binoculars: "lrOptics",
};
