export const KITS = {
	BREACHER: {
		name: "Explosive Entry Specialist",
		class: ["Assault"],
		img: "/icons/Breacher.svg",
		perk: "Explosive Expert",
		description: null,
		perk1: "Items Area of Effect",
		percentage1: "+20%",
		perk2: "Explosive Damage",
		percentage2: "+20%",
		perk3: "Throw Range",
		percentage3: "+60%",
	},
	BREACHER2: {
		name: "Combat Shotgun Specialist",
		class: ["Engineer"],
		img: "/icons/Breacher.svg",
		perk: "Guerrilla",
		description: "For every hit with the shotgun:",
		perk1: "Damage Resistance",
		percentage1: "+10%",
		perk2: "Health Regen Speed",
		percentage2: "+20%",
		perk3: null,
		percentage3: null,
	},
	CBRN: {
		name: "Chemical Defense Specialist",
		class: ["Engineer"],
		img: "/icons/CBRN.svg",
		perk: "Cold Blooded",
		description: null,
		perk1: "Health Regen Delay",
		percentage1: "-30%",
		perk2: "Health Regen Speed",
		percentage2: "+100%",
		perk3: null,
		percentage3: null,
	},
	COMMS: {
		name: "Signals Intelligence Operator",
		class: ["Echelon"],
		img: "/icons/Comms.svg",
		perk: "Sixth Sense",
		description: null,
		perk1: "Automatic Marking",
		percentage1: "+25m",
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	COMMS2: {
		name: "Field Communications Engineer",
		class: ["Engineer"],
		img: "/icons/Comms.svg",
		perk: "Ballistic Advantage",
		description: null,
		perk1: "Range",
		percentage1: "+60%",
		perk2: "Handling",
		percentage2: "+30%",
		perk3: null,
		percentage3: null,
	},
	EW: {
		name: "Electronic Warfare Operator",
		class: ["Panther"],
		img: "/icons/Cyber.svg",
		perk: "Slime Shadow",
		description: null,
		perk1: "Stealth",
		percentage1: "+80%",
		perk2: "Agility",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	EW2: {
		name: "Drone Warfare Specialist",
		class: ["Engineer"],
		img: "/icons/Cyber.svg",
		perk: "Sensor Hack",
		description: null,
		perk1: "Drone Evasion",
		percentage1: "+30%",
		perk2: "Damage to drones",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	EW3: {
		name: "Cyber Operations Specialist",
		class: ["Echelon"],
		img: "/icons/Cyber.svg",
		perk: "Sixth Sense",
		description: null,
		perk1: "Automatic Marking",
		percentage1: "+25m",
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	LEAD: {
		name: "Team Leader",
		class: ["Assault"],
		img: "/icons/default.svg",
		perk: "Inspired",
		description:
			"For every kill by an ally, instantly heal back some of your health.",
		perk1: null,
		percentage1: null,
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	LEAD2: {
		name: "Logistics Coordinator",
		class: ["Engineer"],
		img: "/icons/default.svg",
		perk: "Pack Mule",
		description: null,
		perk1: "Maximum Ammo",
		percentage1: "+40%",
		perk2: "Ammo Pick Up",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	LEAD3: {
		name: "Reconnaissance Team Leader",
		class: ["Echelon"],
		img: "/icons/default.svg",
		perk: "Sixth Sense",
		description: null,
		perk1: "Automatic Marking",
		percentage1: "+25m",
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	LEAD4: {
		name: "Special Operations Team Leader",
		class: ["Panther"],
		img: "/icons/default.svg",
		perk: "Slime Shadow",
		description: null,
		perk1: "Stealth",
		percentage1: "+80%",
		perk2: "Agility",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	LEAD5: {
		name: "Reconnaissance Drone Operator",
		class: ["Pathfinder"],
		img: "/icons/default.svg",
		perk: "Recon Mastery",
		description: "For every enemy marked with your drone:",
		perk1: "Technique Cool-down",
		percentage1: "-15%",
		perk2: "XP Gain",
		percentage2: "+50",
		perk3: null,
		percentage3: null,
	},
	LEAD6: {
		name: "Combat Medic Leader",
		class: ["Medic"],
		img: "/icons/default.svg",
		perk: "Revivalist",
		description: null,
		perk1: "Movement Speed",
		percentage1: "+20%",
		perk2: "Damage Resistance",
		percentage2: "+40%",
		perk3: null,
		percentage3: null,
	},
	LEAD7: {
		name: "Sniper Team Leader",
		class: ["Sharpshooter"],
		img: "/icons/default.svg",
		perk: "Ballistic Advantage",
		description: null,
		perk1: "Range",
		percentage1: "+60%",
		perk2: "Handling",
		percentage2: "+30%",
		perk3: null,
		percentage3: null,
	},
	CE: {
		name: "Demolition Engineer",
		class: ["Engineer"],
		img: "/icons/Demo.svg",
		perk: "Pack Mule",
		description: null,
		perk1: "Maximum Ammo",
		percentage1: "+40%",
		perk2: "Ammo Pick Up",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	DRONE: {
		name: "Unmanned Aerial Vehicle Operator",
		class: ["Engineer"],
		img: "/icons/Drone.svg",
		perk: "Sensor Hack",
		description: null,
		perk1: "Drone Evasion",
		percentage1: "+30%",
		perk2: "Damage to drones",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	DRONE2: {
		name: "Advanced Drone Specialist",
		class: ["Pathfinder"],
		img: "/icons/Drone.svg",
		perk: "Drone Hunter",
		description:
			"After destroying a drone, instantly heal back some of your health.",
		perk1: null,
		percentage1: null,
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	EOD: {
		name: "Explosive Ordnance Specialist",
		class: ["Assault"],
		img: "/icons/EOD.svg",
		perk: "Feel No Pain",
		description: "Relentless:",
		perk1: "Injury Resistance",
		percentage1: "+50%",
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	EOD2: {
		name: "Ordnance Disposal Technician",
		class: ["Engineer"],
		img: "/icons/EOD.svg",
		perk: "Explosive Expert",
		description: null,
		perk1: "Items Area of Effect",
		percentage1: "+20%",
		perk2: "Explosive Damage",
		percentage2: "+20%",
		perk3: "Throw Range",
		percentage3: "+60%",
	},
	GUNNER: {
		name: "Heavy Weapons Specialist",
		class: ["Assault"],
		img: "/icons/Gunner.svg",
		perk: "Rolling Thunder",
		description: null,
		perk1: "Weapon Damage",
		percentage1: "+20%",
		perk2: "Damage to drones",
		percentage2: "+20%",
		perk3: null,
		percentage3: null,
	},
	JTAC: {
		name: "Joint Fires Observer",
		class: ["Pathfinder"],
		img: "/icons/JTAC.svg",
		perk: "Sixth Sense",
		description: null,
		perk1: "Automatic Marking",
		percentage1: "+25m",
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	JTAC2: {
		name: "Forward Air Controller",
		class: ["Assault"],
		img: "/icons/JTAC.svg",
		perk: "Recon Mastery",
		description: "For every enemy marked with your drone:",
		perk1: "Technique Cool-down",
		percentage1: "-15%",
		perk2: "XP Gain",
		percentage2: "+50",
		perk3: null,
		percentage3: null,
	},
	JTAC3: {
		name: "Air Support Coordinator",
		class: ["Echelon"],
		img: "/icons/JTAC.svg",
		perk: "Recon Mastery",
		description: "For ever enemy marked with your drone:",
		perk1: "Technique Cool-down",
		percentage1: "-15%",
		perk2: "XP Gain",
		percentage2: "+50",
		perk3: null,
		percentage3: null,
	},
	MEDIC: {
		name: "Combat Medic",
		class: ["Medic"],
		img: "/icons/Medic.svg",
		perk: "Revivalist",
		description: null,
		perk1: "Movement Speed",
		percentage1: "+20%",
		perk2: "Damage Resistance",
		percentage2: "+40%",
		perk3: null,
		percentage3: null,
	},
	MEDIC2: {
		name: "Field Medic",
		class: ["Engineer"],
		img: "/icons/Medic.svg",
		perk: "Cold Blooded",
		description: null,
		perk1: "Health Regen Delay",
		percentage1: "-30%",
		perk2: "Health Regen Speed",
		percentage2: "+100%",
		perk3: null,
		percentage3: null,
	},
	MEDIC3: {
		name: "Tactical Medic",
		class: ["Assault"],
		img: "/icons/Medic.svg",
		perk: "Inspired",
		description:
			"For every kill by an ally, instantly heal back some of your health.",
		perk1: null,
		percentage1: null,
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	PILOT: {
		name: "Aviation Operations Specialist",
		class: ["Engineer"],
		img: "/icons/Pilot.svg",
		perk: "Pack Mule",
		description: null,
		perk1: "Maximum Ammo",
		percentage1: "+40%",
		perk2: "Ammo Pick Up",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	PILOT2: {
		name: "Rotary-Wing Pilot",
		class: ["Pathfinder"],
		img: "/icons/Pilot.svg",
		perk: "Pistolero",
		description: "While using a handgun:",
		perk1: "Damage",
		percentage1: "+20%",
		perk2: "Technique Cool-down",
		percentage2: "-20%",
		perk3: "XP Bonus",
		percentage3: "+40%",
	},
	SNIPER: {
		name: "Long-Range Marksman",
		class: ["Sharpshooter"],
		img: "/icons/Sniper.svg",
		perk: "Ballistic Advantage",
		description: null,
		perk1: "Range",
		percentage1: "+60%",
		perk2: "Handling",
		percentage2: "+30%",
		perk3: null,
		percentage3: null,
	},
	SIGINT: {
		name: "Signals Intelligence Analyst",
		class: ["Echelon"],
		img: "/icons/Sigint.svg",
		perk: "Recon Mastery",
		description: "For ever enemy marked with your drone:",
		perk1: "Technique Cool-down",
		percentage1: "-15%",
		perk2: "XP Gain",
		percentage2: "+50",
		perk3: null,
		percentage3: null,
	},
	SIGINT2: {
		name: "Electronic Surveillance Operator",
		class: ["Pathfinder"],
		img: "/icons/Sigint.svg",
		perk: "Sixth Sense",
		description: null,
		perk1: "Automatic Marking",
		percentage1: "+25m",
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	CQC: {
		name: "Close Quarters Battle Specialist",
		class: ["Assault"],
		img: "/icons/CQC.svg",
		perk: "Adrenaline",
		description: "After a CQC kill:",
		perk1: "Health Restore",
		percentage1: "+20%",
		perk2: "Reload Speed",
		percentage2: "+40%",
		perk3: "Accuracy",
		percentage3: "+40%",
	},
	CQC2: {
		name: "Urban Combat Specialist",
		class: ["Panther"],
		img: "/icons/CQC.svg",
		perk: "Close and Personal",
		description: null,
		perk1: "Reload Speed",
		percentage1: "+15%",
		perk2: "Mobility",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	INFILTRATOR: {
		name: "Covert Operations Specialist",
		class: ["Panther"],
		img: "/icons/Infiltrator.svg",
		perk: "Slime Shadow",
		description: null,
		perk1: "Stealth",
		percentage1: "+80%",
		perk2: "Agility",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	INFILTRATOR2: {
		name: "Stealth Reconnaissance Operator",
		class: ["Echelon"],
		img: "/icons/Infiltrator.svg",
		perk: "Sensor Hack",
		description: null,
		perk1: "Drone Evasion",
		percentage1: "+30%",
		perk2: "Damage to drones",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	MARKSMAN: {
		name: "Designated Marksman",
		class: ["Sharpshooter"],
		img: "/icons/Marksman.svg",
		perk: "Gunslinger",
		description: null,
		perk1: "Accuracy",
		percentage1: "+15%",
		perk2: "Handling",
		percentage2: "+15%",
		perk3: null,
		percentage3: null,
	},
	DIVER: {
		name: "Amphibious Operations Specialist",
		class: ["Pathfinder"],
		img: "/icons/Diver.svg",
		perk: "Burst Forth",
		description: null,
		perk1: "Movement Speed",
		percentage1: "+10%",
		perk2: "Stamina Regen Speed",
		percentage2: "+50%",
		perk3: null,
		percentage3: null,
	},
	DIVER2: {
		name: "Underwater Demolitions Expert",
		class: ["Pathfinder"],
		img: "/icons/Diver.svg",
		perk: "Cold Blooded",
		description: null,
		perk1: "Health Regen Delay",
		percentage1: "-30%",
		perk2: "Health Regen Speed",
		percentage2: "+100%",
		perk3: null,
		percentage3: null,
	},
	MOUNTAINEER: {
		name: "Mountain Warfare Specialist",
		class: ["Pathfinder"],
		img: "/icons/Mountaineer.svg",
		perk: "Burst Forth",
		description: null,
		perk1: "Movement Speed",
		percentage1: "+10%",
		perk2: "Stamina Regen Speed",
		percentage2: "+50%",
		perk3: null,
		percentage3: null,
	},
	MOUNTAINEER2: {
		name: "High-Altitude Sniper",
		class: ["Sharpshooter"],
		img: "/icons/Mountaineer.svg",
		perk: "Ballistic Advantage",
		description: null,
		perk1: "Range",
		percentage1: "+60%",
		perk2: "Handling",
		percentage2: "+30%",
		perk3: null,
		percentage3: null,
	},

	POINTMAN: {
		name: "Vanguard Operator",
		class: ["Assault"],
		img: "/icons/PointMan.svg",
		perk: "Feel No Pain",
		description: "Relentless:",
		perk1: "Injury Resistance",
		percentage1: "+50%",
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	POINTMAN2: {
		name: "Entry Specialist",
		class: ["Panther"],
		img: "/icons/PointMan.svg",
		perk: "Close and Personal",
		description: null,
		perk1: "Reload Speed",
		percentage1: "+15%",
		perk2: "Mobility",
		percentage2: "+10%",
		perk3: null,
		percentage3: null,
	},
	RECON: {
		name: "Reconnaissance Specialist",
		class: ["Pathfinder"],
		img: "/icons/Recon.svg",
		perk: "Recon Mastery",
		description: "For every enemy marked with your drone:",
		perk1: "Technique Cool-down",
		percentage1: "-15%",
		perk2: "XP Gain",
		percentage2: "+50",
		perk3: null,
		percentage3: null,
	},
	RECON2: {
		name: "Surveillance Operator",
		class: ["Echelon"],
		img: "/icons/Recon.svg",
		perk: "Sixth Sense",
		description: null,
		perk1: "Automatic Marking",
		percentage1: "+25m",
		perk2: null,
		percentage2: null,
		perk3: null,
		percentage3: null,
	},
	RECON3: {
		name: "Scout Sniper",
		class: ["Sharpshooter"],
		img: "/icons/Recon.svg",
		perk: "Gunslinger",
		description: null,
		perk1: "Accuracy",
		percentage1: "+15%",
		perk2: "Handling",
		percentage2: "+15%",
		perk3: null,
		percentage3: null,
	},
};
