export const PERKS = [
	"Pack Mule",
	"Pistolero",
	"Close & Personal",
	"Explosive Expert",
	"Sixth Sense",
	"Sensor Hack",
	"Slim Shadow",
	"Burst Forth",
	"Recon Mastery",
	"Adrenaline",
	"Guerilla",
	"Cold Blooded",
	"Feel No Pain",
	"Revivalist",
	"Inspired",
	"Ballistic Advantage",
	"Rolling Thunder",
	"Gunslinger",
	"Drone Hunter",
];
