export const PERKS = {
	"Pack Mule": "/icons/packMule.svg",
	Pistolero: "/icons/pistolero.svg",
	"Close & Personal": "/icons/closeAndPersonal.svg",
	"Explosive Expert": "/icons/explosiveExpert.svg",
	"Sixth Sense": "/icons/sixthSense.svg",
	"Sensor Hack": "/icons/sensorHack.svg",
	"Slim Shadow": "/icons/slimShadow.svg",
	"Burst Forth": "/icons/burstForth.svg",
	"Recon Mastery": "/icons/reconMastery.svg",
	Adrenaline: "/icons/adrenaline.svg",
	Guerilla: "/icons/guerilla.svg",
	"Cold Blooded": "/icons/coldBlooded.svg",
	"Feel No Pain": "/icons/feelNoPain.svg",
	Revivalist: "/icons/revivalist.svg",
	Inspired: "/icons/inspired.svg",
	"Ballistic Advantage": "/icons/ballisticAdvantage.svg",
	"Rolling Thunder": "/icons/rollingThunder.svg",
	Gunslinger: "/icons/gunslinger.svg",
	"Drone Hunter": "/icons/droneHunter.svg",
};
