// ─────────────────────────────────────────────────────────────────────────────
// PROVINCE TERRAIN CONFIG
// Generated by visual analysis of all 19 map images.
// Coordinate system: [row, col] = [y, x], bounds [0,0] → [768,1366]
// Water rectangles are conservative — slightly inset from true edges
// to give AI safe placement margins for infil/exfil points.
// ─────────────────────────────────────────────────────────────────────────────

// ── 1. CapeNorth ─────────────────────────────────────────────────────────────
// Full island chain. Ocean all sides. Adventure Channel south.
// Twin Islands west. Anchorage Island / Greenfield Plain southeast.
export const CapeNorth_terrain = {
	isIsland: true,
	hasCoast: true,
	coastZones: [
		{
			side: "north",
			bounds: [
				[0, 300],
				[140, 1100],
			],
			label: "Northern Shore",
		},
		{
			side: "south",
			bounds: [
				[600, 100],
				[768, 1200],
			],
			label: "Adventure Channel / Southern Shore",
		},
		{
			side: "west",
			bounds: [
				[100, 0],
				[650, 220],
			],
			label: "Western Ocean / Twin Islands",
		},
		{
			side: "east",
			bounds: [
				[0, 1050],
				[768, 1366],
			],
			label: "Eastern Shore / Anchorage Island",
		},
	],
	inlandWater: [
		{
			label: "Lake Kathryn (center)",
			bounds: [
				[360, 460],
				[520, 640],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"Full island chain. Ocean accessible all sides. Adventure Channel along south provides stealthy boat approach. Lake Kathryn is inland only — not a coast insertion point.",
};

// ── 2. DriftwoodIslets ───────────────────────────────────────────────────────
// Eastern sub-province on same Cape North island. Ocean east/south/north.
export const DriftwoodIslets_terrain = {
	isIsland: true,
	hasCoast: true,
	coastZones: [
		{
			side: "north",
			bounds: [
				[0, 300],
				[140, 1366],
			],
			label: "Northern Shore",
		},
		{
			side: "south",
			bounds: [
				[600, 300],
				[768, 1366],
			],
			label: "Southern Shore",
		},
		{
			side: "east",
			bounds: [
				[0, 1050],
				[768, 1366],
			],
			label: "Eastern Ocean",
		},
	],
	inlandWater: [],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"Eastern portion of the Cape North island chain. Ocean north, south, east. Dense rainforest interior. Boat insertion viable from any coast.",
};

// ── 3. Channels ──────────────────────────────────────────────────────────────
// Left portion is open ocean/fjord. Leviathan, Long, Harbour Islands in water.
// Right side transitions to mainland. Dense channel network center.
export const Channels_terrain = {
	isIsland: false,
	hasCoast: true,
	coastZones: [
		{
			side: "west",
			bounds: [
				[0, 50],
				[768, 320],
			],
			label: "Western Fjord / Open Ocean",
		},
		{
			side: "north",
			bounds: [
				[0, 50],
				[120, 800],
			],
			label: "Northern Channel Entrance",
		},
	],
	inlandWater: [
		{
			label: "Fjord channel network (center)",
			bounds: [
				[80, 200],
				[550, 700],
			],
		},
		{
			label: "Harbour Channel (center)",
			bounds: [
				[300, 400],
				[580, 650],
			],
		},
		{
			label: "Inner island waterways",
			bounds: [
				[150, 250],
				[480, 500],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"Fjordland province. West is open ocean with island chains. Dense navigable channel network throughout center. Boat insertion viable from west coast or any channel. No ocean east or south.",
};

// ── 4. FenBog ────────────────────────────────────────────────────────────────
// Albatross Channel (ocean) on far east. Inland marsh/river network throughout.
export const FenBog_terrain = {
	isIsland: false,
	hasCoast: true,
	coastZones: [
		{
			side: "east",
			bounds: [
				[0, 1080],
				[768, 1366],
			],
			label: "Albatross Channel / Eastern Coast",
		},
		{
			side: "north",
			bounds: [
				[0, 900],
				[100, 1366],
			],
			label: "Northeastern Shore",
		},
	],
	inlandWater: [
		{
			label: "Lake Roundabout (north-center)",
			bounds: [
				[60, 700],
				[180, 900],
			],
		},
		{
			label: "Summer Swamp / marsh delta",
			bounds: [
				[270, 550],
				[600, 1000],
			],
		},
		{
			label: "Diamond Lake (center)",
			bounds: [
				[310, 560],
				[420, 700],
			],
		},
		{
			label: "Lake Mary (west)",
			bounds: [
				[240, 80],
				[360, 200],
			],
		},
		{
			label: "River channels (throughout)",
			bounds: [
				[100, 300],
				[700, 900],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"Salt marsh province. Ocean only on east edge. Extensive inland marshes and river channels allow small boat movement throughout interior. Primary insertion: east coast or inland waterways.",
};

// ── 5. GolemIsland (Golem1, Golem2, Golem3) ──────────────────────────────────
// Classic volcanic island. Ocean all four sides. No inland water.
export const GolemIsland_terrain = {
	isIsland: true,
	hasCoast: true,
	coastZones: [
		{
			side: "north",
			bounds: [
				[0, 200],
				[120, 1100],
			],
			label: "Northern Shore",
		},
		{
			side: "south",
			bounds: [
				[580, 100],
				[768, 1200],
			],
			label: "Southern Shore",
		},
		{
			side: "west",
			bounds: [
				[80, 0],
				[700, 180],
			],
			label: "Western Coast",
		},
		{
			side: "east",
			bounds: [
				[50, 1100],
				[680, 1366],
			],
			label: "Eastern Coast",
		},
	],
	inlandWater: [],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"Volcanic island. Ocean all sides. Lava terrain on eastern volcano face limits eastern landing — prefer north or west coast insertion. Southern shore has small offshore islet.",
};

// ── 6. GoodHopeMountain ───────────────────────────────────────────────────────
// Fully inland high tundra. Far west river strip from adjacent province.
// Alpine lakes east side. No ocean.
export const GoodHopeMountain_terrain = {
	isIsland: false,
	hasCoast: false,
	coastZones: [],
	inlandWater: [
		{
			label: "Western river strip (adjacent province edge)",
			bounds: [
				[0, 0],
				[768, 80],
			],
		},
		{
			label: "Alpine lakes (east)",
			bounds: [
				[130, 900],
				[420, 1200],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"High tundra inland province. No ocean. No coast. Ground vehicle or HALO/LALO only. Western river edge is not accessible for insertion from this province.",
};

// ── 7. Infinity ───────────────────────────────────────────────────────────────
// Resolution Channel east (col ~870+). Dolphin Bay cuts deeply inland south.
// North and west are inland. Small offshore islet south.
export const Infinity_terrain = {
	isIsland: false,
	hasCoast: true,
	coastZones: [
		{
			side: "east",
			bounds: [
				[0, 870],
				[768, 1366],
			],
			label: "Resolution Channel / Eastern Coast",
		},
		{
			side: "south",
			bounds: [
				[500, 300],
				[768, 870],
			],
			label: "Dolphin Bay / Southern Harbor",
		},
	],
	inlandWater: [
		{
			label: "Dolphin Bay (large inland bay)",
			bounds: [
				[440, 350],
				[700, 750],
			],
		},
		{
			label: "Small lake (far northwest)",
			bounds: [
				[0, 100],
				[80, 350],
			],
		},
	],
	hasRoads: true,
	hasAirfield: true,
	notes:
		"Urban coastal city. Resolution Channel east, Dolphin Bay penetrates deep south into city. Boat insertion viable from east coast or directly into Dolphin Bay near city center. Shelter Island offshore south.",
};

// ── 8. LakeCountry ────────────────────────────────────────────────────────────
// Fully inland. Blackwater Lake north-center, Flock Lake center, others.
// No ocean anywhere.
export const LakeCountry_terrain = {
	isIsland: false,
	hasCoast: false,
	coastZones: [],
	inlandWater: [
		{
			label: "Blackwater Lake (north-center)",
			bounds: [
				[40, 480],
				[170, 680],
			],
		},
		{
			label: "Trough Lake (west)",
			bounds: [
				[270, 50],
				[430, 190],
			],
		},
		{
			label: "Flock Lake (center)",
			bounds: [
				[350, 220],
				[530, 430],
			],
		},
		{
			label: "Garner Lake / Harper Lake",
			bounds: [
				[310, 620],
				[470, 820],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"Inland lake province. No ocean. Multiple large lakes but no coast insertion available. Ground vehicle or air insertion only.",
};

// ── 9. Liberty ────────────────────────────────────────────────────────────────
// Resolution Channel east (col ~920+). Dolphin Bay south.
// Liberty Airport northwest. Small isolated islet south of city.
export const Liberty_terrain = {
	isIsland: false,
	hasCoast: true,
	coastZones: [
		{
			side: "east",
			bounds: [
				[0, 920],
				[768, 1366],
			],
			label: "Resolution Channel / Eastern Coast",
		},
		{
			side: "south",
			bounds: [
				[560, 200],
				[768, 920],
			],
			label: "Dolphin Bay / Southern Shore",
		},
	],
	inlandWater: [
		{
			label: "Dolphin Bay / Liberty Harbor",
			bounds: [
				[490, 280],
				[700, 720],
			],
		},
		{
			label: "Beach Lake (far northwest)",
			bounds: [
				[0, 120],
				[90, 290],
			],
		},
		{
			label: "City water channels",
			bounds: [
				[380, 280],
				[560, 600],
			],
		},
	],
	hasRoads: true,
	hasAirfield: true,
	notes:
		"Urban coastal province. Resolution Channel east, Dolphin Bay south. Liberty Airport northwest. Boat insertion via east coast or Dolphin Bay into urban area. Shelter Island offshore south.",
};

// ── 10. MountHodgson ─────────────────────────────────────────────────────────
// Fully inland glacial terrain. Multiple alpine lakes. No ocean.
export const MountHodgson_terrain = {
	isIsland: false,
	hasCoast: false,
	coastZones: [],
	inlandWater: [
		{
			label: "Cold Lake (north-center)",
			bounds: [
				[30, 470],
				[120, 560],
			],
		},
		{
			label: "Sun Lake (west)",
			bounds: [
				[100, 60],
				[210, 200],
			],
		},
		{
			label: "Moon Lake (center)",
			bounds: [
				[310, 490],
				[410, 590],
			],
		},
		{
			label: "Lake Mary (east)",
			bounds: [
				[390, 920],
				[530, 1080],
			],
		},
		{
			label: "Trough / Flock Lakes (east)",
			bounds: [
				[230, 800],
				[500, 980],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"High tundra mountain province. No ocean. HALO/LALO or ground vehicle insertion only. Alpine lakes are not tactically usable for boat insertion.",
};

// ── 11. NewArgyll ────────────────────────────────────────────────────────────
// Albatross Channel east (col ~1100+). Interior swamp/marsh/river network.
export const NewArgyll_terrain = {
	isIsland: false,
	hasCoast: true,
	coastZones: [
		{
			side: "east",
			bounds: [
				[0, 1100],
				[768, 1366],
			],
			label: "Eastern Coast / Albatross Channel",
		},
	],
	inlandWater: [
		{
			label: "Summer Swamp / river delta (east-center)",
			bounds: [
				[200, 550],
				[620, 1050],
			],
		},
		{
			label: "Lake Mary (northwest)",
			bounds: [
				[60, 100],
				[200, 290],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"Rain shadows province. Ocean east coast only. Dense swamp and river network in east-center — small boat movement possible through marshes. Western mountains are landlocked.",
};

// ── 12. NewStirling ──────────────────────────────────────────────────────────
// Ocean east edge (col ~1030+). Farmland/meadow interior. Small scattered lakes.
export const NewStirling_terrain = {
	isIsland: false,
	hasCoast: true,
	coastZones: [
		{
			side: "east",
			bounds: [
				[0, 1030],
				[768, 1366],
			],
			label: "Eastern Coastline",
		},
	],
	inlandWater: [
		{
			label: "Small lake cluster (center)",
			bounds: [
				[250, 380],
				[420, 560],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"Meadow farmland province. Ocean only on east edge. Ground vehicle primary insertion. Boat insertion only viable from east coast approach.",
};

// ── 13. RestrictedArea01 ─────────────────────────────────────────────────────
// Inland highland. Blue Lake large center-left. Small Lake lower center.
// Mirror Lake / river far west edge. No ocean.
export const RestrictedArea01_terrain = {
	isIsland: false,
	hasCoast: false,
	coastZones: [],
	inlandWater: [
		{
			label: "Blue Lake (center-large)",
			bounds: [
				[200, 280],
				[500, 580],
			],
		},
		{
			label: "Small Lake (lower center)",
			bounds: [
				[430, 290],
				[530, 420],
			],
		},
		{
			label: "Mirror Lake / west edge",
			bounds: [
				[620, 0],
				[768, 100],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"Restricted highland province. No ocean. Blue Lake large enough for staging near shore but not an insertion route. Ground vehicle or HALO/LALO primary. Mountainous terrain favors air insertion.",
};

// ── 14. SealIslands ──────────────────────────────────────────────────────────
// Island cluster. Ocean north, west, south. Anchor Island and Hunter Island offshore.
// East connects to Liberty mainland. Naval base southwest.
export const SealIslands_terrain = {
	isIsland: true,
	hasCoast: true,
	coastZones: [
		{
			side: "north",
			bounds: [
				[0, 50],
				[140, 1100],
			],
			label: "Northern Shore / Bad Channel",
		},
		{
			side: "south",
			bounds: [
				[620, 50],
				[768, 900],
			],
			label: "Southern Shore / Hunter Island",
		},
		{
			side: "west",
			bounds: [
				[50, 0],
				[700, 200],
			],
			label: "Western Ocean / Anchor Island",
		},
	],
	inlandWater: [
		{
			label: "Harbour Channel (center between islands)",
			bounds: [
				[130, 200],
				[460, 700],
			],
		},
	],
	hasRoads: true,
	hasAirfield: true,
	notes:
		"Island cluster. Ocean north, west, south. Naval base southwest — amphibious insertion prime. Airfield present. Channel between main islands navigable. East edge connects to Liberty mainland.",
};

// ── 15. SilentMountain ───────────────────────────────────────────────────────
// Fully inland. Blue Lake dominates center. River valley channels west.
// No ocean anywhere.
export const SilentMountain_terrain = {
	isIsland: false,
	hasCoast: false,
	coastZones: [],
	inlandWater: [
		{
			label: "Blue Lake (large, center)",
			bounds: [
				[180, 240],
				[540, 620],
			],
		},
		{
			label: "Small Lake (south of Blue)",
			bounds: [
				[430, 270],
				[530, 390],
			],
		},
		{
			label: "River valley (west approach)",
			bounds: [
				[100, 0],
				[550, 180],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"High tundra mountain province. No ocean. Blue Lake is large — near-shore staging possible but no coast insertion. Ground vehicle or HALO/LALO primary.",
};

// ── 16. SinkingCountry ───────────────────────────────────────────────────────
// Typhoon Bay (ocean) on north (rows 0–165). East coast (col ~1050+).
// Anchorage Island offshore northeast. Dense interior salt marsh.
export const SinkingCountry_terrain = {
	isIsland: false,
	hasCoast: true,
	coastZones: [
		{
			side: "north",
			bounds: [
				[0, 200],
				[165, 1000],
			],
			label: "Typhoon Bay / Northern Shore",
		},
		{
			side: "east",
			bounds: [
				[0, 1050],
				[768, 1366],
			],
			label: "Eastern Coast / Anchorage Island",
		},
	],
	inlandWater: [
		{
			label: "Marsh river delta (center)",
			bounds: [
				[150, 280],
				[580, 900],
			],
		},
		{
			label: "Lake Roundabout (center-east)",
			bounds: [
				[290, 660],
				[420, 820],
			],
		},
		{
			label: "Diamond Lake (lower center)",
			bounds: [
				[470, 510],
				[590, 680],
			],
		},
		{
			label: "Dead Horse Swamp (northwest)",
			bounds: [
				[200, 180],
				[340, 380],
			],
		},
	],
	hasRoads: true,
	hasAirfield: true,
	notes:
		"Salt marsh coastal province. Typhoon Bay northern boat insertion. East coast secondary. Dense marsh interior allows inland water movement. Howard Airfield on east side.",
};

// ── 17. SmugglersCoves ───────────────────────────────────────────────────────
// Adventure Channel on north (top rows 0–150). West edge is ocean.
// Cliff terrain. No ocean south or east.
export const SmugglersCoves_terrain = {
	isIsland: false,
	hasCoast: true,
	coastZones: [
		{
			side: "north",
			bounds: [
				[0, 0],
				[150, 1366],
			],
			label: "Adventure Channel / Northern Shore",
		},
		{
			side: "west",
			bounds: [
				[100, 0],
				[768, 150],
			],
			label: "Western Ocean / Cliff Coast",
		},
	],
	inlandWater: [],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"High cliffs coastal province. Adventure Channel north — boat insertion along coves viable. Western cliff coast has limited landing spots. No inland water. Cliff terrain restricts vehicle movement near coast.",
};

// ── 18. WhalersBay ───────────────────────────────────────────────────────────
// Whales Bank ocean on west (col 0–280). Petrel Island offshore southwest.
// Kraken Eye Lake and Loch Lake are inland freshwater only.
export const WhalersBay_terrain = {
	isIsland: false,
	hasCoast: true,
	coastZones: [
		{
			side: "west",
			bounds: [
				[0, 0],
				[768, 280],
			],
			label: "Whales Bank / Western Ocean",
		},
	],
	inlandWater: [
		{
			label: "Kraken Eye Lake (center-west)",
			bounds: [
				[260, 270],
				[430, 430],
			],
		},
		{
			label: "Loch Lake (south-center)",
			bounds: [
				[510, 340],
				[620, 460],
			],
		},
	],
	hasRoads: true,
	hasAirfield: true,
	notes:
		"High cliffs province. Western ocean via Whales Bank. Petrel Island offshore — amphibious staging viable. Bay between Petrel Island and mainland is prime boat insertion zone. Airfield inland center.",
};

// ── 19. WildCoast ────────────────────────────────────────────────────────────
// Ocean on west (col 0–250). Stubb Bay inlet cuts into northern interior.
// Pecho Dick Heights peninsula juts into the bay. No ocean east or south.
export const WildCoast_terrain = {
	isIsland: false,
	hasCoast: true,
	coastZones: [
		{
			side: "west",
			bounds: [
				[0, 0],
				[768, 250],
			],
			label: "Wild Coast / Western Ocean",
		},
		{
			side: "north",
			bounds: [
				[0, 80],
				[320, 530],
			],
			label: "Stubb Bay / Northern Inlet",
		},
	],
	inlandWater: [
		{
			label: "Stubb Bay inlet (deep penetration)",
			bounds: [
				[80, 170],
				[350, 500],
			],
		},
		{
			label: "Lake Bulkington (inland only)",
			bounds: [
				[400, 200],
				[540, 360],
			],
		},
	],
	hasRoads: true,
	hasAirfield: false,
	notes:
		"Coastal province. Western ocean and Stubb Bay inlet allow boat insertion deep into northwest interior. Pecho Dick Heights makes good overwatch for bay insertion. Lake Bulkington is inland only.",
};

// ── 20. WindyIslands ─────────────────────────────────────────────────────────
// Pure island cluster. Entire map is ocean with islands.
// Eggs Island north, Shark Island center, Whalers Island southwest.
// Cemetery Island, Captain John Island. Dense small islets.
export const WindyIslands_terrain = {
	isIsland: true,
	hasCoast: true,
	coastZones: [
		{
			side: "north",
			bounds: [
				[0, 150],
				[180, 1200],
			],
			label: "Northern Ocean / Eggs Island waters",
		},
		{
			side: "south",
			bounds: [
				[580, 100],
				[768, 1100],
			],
			label: "Southern Ocean / Whalers Island",
		},
		{
			side: "west",
			bounds: [
				[0, 0],
				[768, 200],
			],
			label: "Western Ocean",
		},
		{
			side: "east",
			bounds: [
				[0, 850],
				[768, 1366],
			],
			label: "Eastern Ocean / Dolphin Bay approach",
		},
	],
	inlandWater: [],
	hasRoads: false,
	hasAirfield: false,
	notes:
		"Pure island archipelago. Ocean surrounds all islands. Boat insertion is the ONLY viable primary method. HALO viable as alternate. No roads — all movement on foot after insertion. Small islets usable as staging points.",
};

// ─────────────────────────────────────────────────────────────────────────────
// TERRAIN MAP — spread into PROVINCES config
// Usage in PROVINCES: terrain: PROVINCE_TERRAIN["CapeNorth"]
// ─────────────────────────────────────────────────────────────────────────────
export const PROVINCE_TERRAIN = {
	CapeNorth: CapeNorth_terrain,
	DriftwoodIslets: DriftwoodIslets_terrain,
	Channels: Channels_terrain,
	FenBog: FenBog_terrain,
	Golem1: GolemIsland_terrain,
	Golem2: GolemIsland_terrain,
	Golem3: GolemIsland_terrain,
	GoodHopeMountain: GoodHopeMountain_terrain,
	Infinity: Infinity_terrain,
	LakeCountry: LakeCountry_terrain,
	Liberty: Liberty_terrain,
	MountHodgson: MountHodgson_terrain,
	NewArgyll: NewArgyll_terrain,
	NewStirling: NewStirling_terrain,
	RestrictedArea01: RestrictedArea01_terrain,
	SealIslands: SealIslands_terrain,
	SilentMountain: SilentMountain_terrain,
	SinkingCountry: SinkingCountry_terrain,
	SmugglersCoves: SmugglersCoves_terrain,
	WhalersBay: WhalersBay_terrain,
	WildCoast: WildCoast_terrain,
	WindyIslands: WindyIslands_terrain,
};
