export const TEAMS = [
	{
		name: "Direct Action",
		lead: "Assault",
		classes: ["Assault", "Assault", "Engineer", "Medic"],
		validClasses: ["Assault", "Engineer", "Medic"],
	},
	{
		name: "Raid",
		lead: "Assault",
		classes: ["Assault", "Assault", "Engineer", "Sharpshooter"],
		validClasses: ["Assault", "Engineer", "Sharpshooter"],
	},
	{
		name: "Stronghold Assault",
		lead: "Assault",
		classes: ["Assault", "Assault", "Engineer", "Medic"],
		validClasses: ["Assault", "Engineer", "Medic"],
	},
	{
		name: "Base Assault",
		lead: "Assault",
		classes: ["Assault", "Engineer", "Medic", "Sharpshooter"],
		validClasses: ["Assault", "Engineer", "Medic", "Sharpshooter"],
	},
	{
		name: "Airfield Seizure",
		lead: "Assault",
		classes: ["Assault", "Assault", "Engineer", "Medic"],
		validClasses: ["Assault", "Engineer", "Medic"],
	},
	{
		name: "HVT Elimination",
		lead: "Echelon",
		classes: ["Echelon", "Sharpshooter", "Panther", "Assault"],
		validClasses: ["Echelon", "Sharpshooter", "Panther", "Assault"],
	},
	{
		name: "HVT Capture",
		lead: "Echelon",
		classes: ["Echelon", "Panther", "Assault", "Medic"],
		validClasses: ["Echelon", "Panther", "Assault", "Medic"],
	},
	{
		name: "Personnel Recovery",
		lead: "Medic",
		classes: ["Medic", "Assault", "Panther", "Engineer"],
		validClasses: ["Medic", "Assault", "Panther", "Engineer"],
	},
	{
		name: "Combat Search and Rescue",
		lead: "Medic",
		classes: ["Medic", "Assault", "Pathfinder", "Engineer"],
		validClasses: ["Medic", "Assault", "Pathfinder", "Engineer"],
	},
	{
		name: "Hostage Rescue",
		lead: "Medic",
		classes: ["Assault", "Panther", "Medic", "Echelon"],
		validClasses: ["Assault", "Panther", "Medic", "Echelon"],
	},
	{
		name: "VIP Extraction",
		lead: "Medic",
		classes: ["Medic", "Assault", "Panther"],
		validClasses: ["Medic", "Assault", "Panther"],
	},
	{
		name: "Noncombatant Evacuation",
		lead: "Medic",
		classes: ["Medic", "Assault", "Engineer", "Pathfinder"],
		validClasses: ["Medic", "Assault", "Engineer", "Pathfinder"],
	},
	{
		name: "Reconnaissance",
		lead: "Pathfinder",
		classes: ["Pathfinder", "Echelon"],
		validClasses: ["Pathfinder", "Echelon"],
	},
	{
		name: "Area Reconnaissance",
		lead: "Pathfinder",
		classes: ["Pathfinder", "Echelon", "Sharpshooter"],
		validClasses: ["Pathfinder", "Echelon", "Sharpshooter"],
	},
	{
		name: "Route Reconnaissance",
		lead: "Pathfinder",
		classes: ["Pathfinder", "Panther"],
		validClasses: ["Pathfinder", "Panther"],
	},
	{
		name: "Special Reconnaissance",
		lead: "Pathfinder",
		classes: ["Pathfinder", "Echelon", "Panther"],
		validClasses: ["Pathfinder", "Echelon", "Panther"],
	},
	{
		name: "Surveillance",
		lead: "Pathfinder",
		classes: ["Pathfinder", "Sharpshooter"],
		validClasses: ["Pathfinder", "Sharpshooter"],
	},
	{
		name: "Observation Post",
		lead: "Sharpshooter",
		classes: ["Sharpshooter", "Pathfinder"],
		validClasses: ["Sharpshooter", "Pathfinder"],
	},
	{
		name: "Battle Damage Assessment",
		lead: "Pathfinder",
		classes: ["Pathfinder", "Echelon"],
		validClasses: ["Pathfinder", "Echelon"],
	},
	{
		name: "Target Designation",
		lead: "Pathfinder",
		classes: ["Pathfinder", "Echelon", "Sharpshooter"],
		validClasses: ["Pathfinder", "Echelon", "Sharpshooter"],
	},
	{
		name: "Intelligence Gathering",
		lead: "Echelon",
		classes: ["Echelon", "Pathfinder", "Panther"],
		validClasses: ["Echelon", "Pathfinder", "Panther"],
	},
	{
		name: "Signals Intelligence",
		lead: "Echelon",
		classes: ["Echelon", "Engineer"],
		validClasses: ["Echelon", "Engineer"],
	},
	{
		name: "Electronic Warfare",
		lead: "Engineer",
		classes: ["Engineer", "Echelon", "Pathfinder"],
		validClasses: ["Engineer", "Echelon", "Pathfinder"],
	},
	{
		name: "Covert Infiltration",
		lead: "Panther",
		classes: ["Panther", "Echelon"],
		validClasses: ["Panther", "Echelon"],
	},
	{
		name: "Covert Exfiltration",
		lead: "Panther",
		classes: ["Panther", "Echelon", "Medic"],
		validClasses: ["Panther", "Echelon", "Medic"],
	},
	{
		name: "Undercover Surveillance",
		lead: "Echelon",
		classes: ["Echelon", "Panther"],
		validClasses: ["Echelon", "Panther"],
	},
	{
		name: "Sabotage",
		lead: "Engineer",
		classes: ["Engineer", "Panther", "Echelon"],
		validClasses: ["Engineer", "Panther", "Echelon"],
	},
	{
		name: "Demolition",
		lead: "Engineer",
		classes: ["Engineer", "Engineer", "Assault"],
		validClasses: ["Engineer", "Assault"],
	},
	{
		name: "Infrastructure Attack",
		lead: "Engineer",
		classes: ["Engineer", "Panther", "Assault"],
		validClasses: ["Engineer", "Panther", "Assault"],
	},
	{
		name: "Drone Hunter",
		lead: "Engineer",
		classes: ["Engineer", "Sharpshooter", "Pathfinder"],
		validClasses: ["Engineer", "Sharpshooter", "Pathfinder"],
	},
	{
		name: "Convoy Ambush",
		lead: "Engineer",
		classes: ["Engineer", "Sharpshooter", "Assault", "Panther"],
		validClasses: ["Engineer", "Sharpshooter", "Assault", "Panther"],
	},
	{
		name: "Vehicle Interdiction",
		lead: "Engineer",
		classes: ["Engineer", "Sharpshooter", "Assault"],
		validClasses: ["Engineer", "Sharpshooter", "Assault"],
	},
	{
		name: "Convoy Escort",
		lead: "Assault",
		classes: ["Assault", "Engineer", "Medic", "Sharpshooter"],
		validClasses: ["Assault", "Engineer", "Medic", "Sharpshooter"],
	},
	{
		name: "Sniper Mission",
		lead: "Sharpshooter",
		classes: ["Sharpshooter", "Echelon"],
		validClasses: ["Sharpshooter", "Echelon"],
	},
	{
		name: "Counter-Sniper",
		lead: "Sharpshooter",
		classes: ["Sharpshooter", "Sharpshooter", "Pathfinder"],
		validClasses: ["Sharpshooter", "Pathfinder"],
	},
	{
		name: "Combat Patrol",
		lead: "Assault",
		classes: ["Assault", "Medic", "Sharpshooter"],
		validClasses: ["Assault", "Medic", "Sharpshooter"],
	},
	{
		name: "Security Operation",
		lead: "Assault",
		classes: ["Assault", "Medic", "Engineer"],
		validClasses: ["Assault", "Medic", "Engineer"],
	},
	{
		name: "Counter-Insurgency",
		lead: "Assault",
		classes: ["Assault", "Medic", "Sharpshooter", "Engineer"],
		validClasses: ["Assault", "Medic", "Sharpshooter", "Engineer"],
	},
	{
		name: "Counter-Terrorism",
		lead: "Assault",
		classes: ["Assault", "Panther", "Medic", "Echelon"],
		validClasses: ["Assault", "Panther", "Medic", "Echelon"],
	},
	{
		name: "Border Interdiction",
		lead: "Pathfinder",
		classes: ["Pathfinder", "Sharpshooter", "Assault"],
		validClasses: ["Pathfinder", "Sharpshooter", "Assault"],
	},
	{
		name: "Counter-Drug Operation",
		lead: "Echelon",
		classes: ["Echelon", "Panther", "Assault"],
		validClasses: ["Echelon", "Panther", "Assault"],
	},
];
