// Weapons configuration for GhostOpsAI loadout system
// Source: Ghost Recon Breakpoint - canonical weapon platforms only
// Variants (Black Ice, Brown, Survival, Wolves, Tactical, etc.) intentionally excluded
// Players can note variants in the loadout name field

export const WEAPON_TYPES = {
	ASR: {
		name: "Assault Rifle",
		imgUrl: "/icons/ASR.svg",
	},
	DMR: {
		name: "Designated Marksman Rifle",
		imgUrl: "/icons/DMR.svg",
	},
	LMG: {
		name: "Light Machine Gun",
		imgUrl: "/icons/LMG.svg",
	},
	SMG: {
		name: "Sub Machine Gun",
		imgUrl: "/icons/SMG.svg",
	},
	SNR: {
		name: "Sniper Rifle",
		imgUrl: "/icons/SNR.svg",
	},
	STG: {
		name: "Shotgun",
		imgUrl: "/icons/STG.svg",
	},
	GNL: {
		name: "Grenade Launcher",
		imgUrl: "/icons/GNL.svg",
	},
	HDG: {
		name: "Handgun",
		imgUrl: "/icons/Sidearm.svg",
	},
};

// Weapons grouped by type. Names match in-game canonical platform names.
// Used to populate the primary/secondary weapon dropdowns.
export const WEAPONS_BY_TYPE = {
	ASR: [
		"4-AC",
		"416",
		"516",
		"553",
		"805 Bren",
		"A2",
		"AC-AR",
		"ACR",
		"AK12",
		"AK47",
		"AK74",
		"AR-18",
		"ARX200",
		"AUG",
		"FAL",
		"G2",
		"G36C",
		"K1A",
		"Koblin",
		"L85-C",
		"M4A1",
		"MDR",
		"MK17",
		"MK18",
		"Resistance ASR",
		"SC-20K",
		"SC-40K",
		"SR-3M",
		"Silver Stake",
		"Tavor",
		"VHSD2",
	],
	DMR: [
		"416 Scout",
		"553 Scout",
		"AK74 Scout",
		"AUG Scout",
		"FRF2",
		"G28",
		"G36C Scout",
		"M110",
		"M4A1 Scout",
		"MK14",
		"MK17 Scout",
		"OTS-03",
		"SR-3M Scout",
		"SVD-63",
		"Scorpio Scout",
		"Tavor Scout",
	],
	SMG: [
		"Bullpup PDR",
		"Echelon SMG",
		"Honey Badger",
		"MP5",
		"MP7",
		"MPX",
		"P90",
		"Scorpion EVO3",
		"SN-9mm",
		"UMP",
		"Uzi 9mm",
		"Vector",
	],
	LMG: ["6P41", "CTMMG", "L86A1", "MG121", "MK48", "Stoner", "T95"],
	SNR: [
		"HTI",
		"L115A3",
		"M82",
		"MSR",
		"Paladin 9 SNR",
		"Recon-A1",
		"SR-1",
		"Scorpio",
		"Tac50",
		"VSK-50",
		"Zastava M93",
	],
	STG: [
		"ACS12",
		"BOSG12",
		"KSG12",
		"M4",
		"M590A1",
		"RU12SG",
		"SASG12",
		"SPAS-12",
	],
	GNL: ["MGL"],
	HDG: [
		"5.7 USG",
		"Bailiff 410",
		"C-SFP",
		"Desert Eagle",
		"F40",
		"M1911",
		"M9",
		"Maxim 9",
		"MK23",
		"P227",
		"P320",
		"P45T",
		"PX4",
		"SC IS HDG",
		"Sharp Thunder",
		"Stainless Extended .45",
		"USP Tactical",
	],
};

// Attachment options grouped by slot. All slots optional on the loadout form.
// Stat effects come from the spreadsheet's Locations & Stats sheet — surface
// these in tooltips on the form for player reference.
export const ATTACHMENTS = {
	barrel: ["Standard Barrel", "Short Barrel"],
	muzzle: [
		"Standard Muzzle",
		"Compensator",
		"Flash Hider",
		"Muzzle Brake",
		"Suppressor",
		"Hive Silencer",
		"Kilim Silencer",
		"Prism Silencer",
		"Ripples Silencer",
		"338 Control Shield",
		"556 Control Shield",
		"762 Control Shield",
	],
	magazine: [
		"Standard Magazine",
		"Extended Magazine",
		"Small Magazine",
		"ASR 100 Rounds Magazine",
	],
	scope: [
		"Ironsight",
		"ACSS Sight",
		"COMPM4 Sight",
		"Digital Sight",
		"Dual Range Sight",
		"EXPS3",
		"EXPS3XG33 Sight",
		"LEUPOLD Holo Sight",
		"MH1 Sight",
		"MICROT1 Sight",
		"MICROT1XG33 Sight",
		"Paladin Optic",
		"Panoramic Sight",
		"RU Collimator Sight",
		"RU Long-Range FOV Sight",
		"RU Long-Range Sight",
		"RU Red Dot Sight",
		"RU Red Dot G33 Sight",
		"SLX5 Sight",
		"T5XI Sight",
		"TA31H Sight",
		"TARS101",
		"VC16 Sight",
		"Futuristic Closed Sight",
		"Futuristic Open View Sight",
	],
	rail: [
		"Rail Cover",
		"PEQ-15",
		"ATPIALx3",
		"ATPIAL HDG Laser",
		"MAWL-DA",
		"Range Finder",
	],
	underbarrel: [
		"Underbarrel Rail (None)",
		"AFG-2 Angled Foregrip",
		"PTK Angled Foregrip",
		"Rounded Angled Foregrip",
		"SHIFT Angled Short Grip",
		"STFG Angled Grip",
		"Vented Angled Foregrip",
		"Lightweight Vertical Foregrip",
		"RU Vertical Foregrip",
		"RVG Vertical Foregrip",
		"SHIFT Vertical Foregrip",
		"Tactical Vertical Foregrip",
		"Bipod",
		"Bipod and Foregrip Combo",
		"Grip Pod",
		"Underbarrel Grenade Launcher",
		"Underbarrel Shotgun",
	],
	stock: [
		"Standard Stock",
		"Adjustable Stock",
		"Short Barrel",
		"Trigger Select",
	],
};

// Mission profile tags for loadout categorization.
// Drives the icon shown on the cycle button and lets players filter later.
export const MISSION_PROFILES = {
	DA: {
		name: "Direct Action",
		description: "Door-kicking, HVT capture, hostage rescue",
	},
	RECON: {
		name: "Recon / Surveillance",
		description: "Long-range observation, pathfinding, intel",
	},
	SAB: {
		name: "Sabotage",
		description: "Covert infrastructure strikes, denial ops",
	},
	SUS: {
		name: "Sustained Combat",
		description: "Extended firefights, defensive ops, support",
	},
	COV: {
		name: "Specialist / Covert",
		description: "Infiltration, assassination, deep cover",
	},
};

// Per-weapon attachment compatibility, parsed from the in-game attachment matrix.
// Each weapon maps to slot -> array of compatible attachment names.
// Empty object = weapon takes no attachments (e.g., MGL).
// Missing slot key = no compatible attachments for that slot on this weapon.
// Use getCompatibleAttachments(weaponName, slot) to query.
export const WEAPON_COMPATIBILITY = {
	"4-AC": {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: [
			"Extended Magazine",
			"Small Magazine",
			"Standard Magazine",
			"ASR 100 Rounds Magazine",
		],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: [
			"A2-M",
			"ARM",
			"CTR",
			"CTR-SLK",
			"Core CP",
			"DD-CB",
			"E1",
			"EMOD",
			"HMM",
			"IMOD",
			"KAC-SASS",
			"M-BRS",
			"M4",
			"MS-U",
			"Mini-CQB",
			"Socom-1",
			"TACLite",
			"UBR Gen2",
		],
	},
	416: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: [
			"Extended Magazine",
			"Small Magazine",
			"Standard Magazine",
			"ASR 100 Rounds Magazine",
		],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
		stock: [
			"A2-M",
			"ARM",
			"CTR",
			"CTR-SLK",
			"Core CP",
			"DD-CB",
			"E1",
			"EMOD",
			"HMM",
			"IMOD",
			"KAC-SASS",
			"M-BRS",
			"M4",
			"MS-U",
			"Mini-CQB",
			"Socom-1",
			"TACLite",
			"UBR Gen2",
		],
	},
	"416 Scout": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Ironsight",
			"Dual Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: [
			"A2-M",
			"ARM",
			"CTR",
			"CTR-SLK",
			"Core CP",
			"DD-CB",
			"E1",
			"EMOD",
			"HMM",
			"IMOD",
			"KAC-SASS",
			"M-BRS",
			"M4",
			"MS-U",
			"Mini-CQB",
			"Socom-1",
			"TACLite",
			"UBR Gen2",
		],
	},
	"5.7 USG": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	516: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
		stock: [
			"A2-M",
			"ARM",
			"CTR",
			"CTR-SLK",
			"Core CP",
			"DD-CB",
			"E1",
			"EMOD",
			"HMM",
			"IMOD",
			"KAC-SASS",
			"M-BRS",
			"M4",
			"MS-U",
			"Mini-CQB",
			"Socom-1",
			"TACLite",
			"UBR Gen2",
		],
	},
	553: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: [
			"Extended Magazine",
			"Small Magazine",
			"Standard Magazine",
			"ASR 100 Rounds Magazine",
		],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
		stock: [
			"553-STK",
			"A2-M",
			"ARM",
			"CTR",
			"CTR-SLK",
			"Core CP",
			"DD-CB",
			"E1",
			"EMOD",
			"HMM",
			"IMOD",
			"M-BRS",
			"M4",
			"MS-U",
			"Socom-1",
			"TACLite",
		],
	},
	"553 Scout": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Dual Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: [
			"553-STK",
			"A2-M",
			"ARM",
			"CTR",
			"CTR-SLK",
			"Core CP",
			"DD-CB",
			"E1",
			"EMOD",
			"HMM",
			"IMOD",
			"M-BRS",
			"M4",
			"MS-U",
			"Socom-1",
			"TACLite",
		],
	},
	"6P41": {
		muzzle: ["Compensator", "Flash Hider", "Muzzle Brake", "Standard Muzzle"],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"MICROT1 Sight",
			"RU Red Dot Sight",
			"SLX5 Sight",
			"TA31H Sight",
		],
		underbarrel: ["Grip Pod", "Tactical Vertical Foregrip"],
	},
	"805 Bren": {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"762 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"MH1 Sight",
			"RU Collimator Sight",
			"RU Red Dot Sight",
			"SLX5 Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
	},
	A2: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"MH1 Sight",
			"RU Collimator Sight",
			"RU Red Dot Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
		stock: ["STK-P", "STK-PC"],
	},
	"AC-AR": {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"762 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"RU Collimator Sight",
			"RU Red Dot Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
		],
		stock: ["Trigger Select", "Short Barrel"],
	},
	ACR: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
		stock: ["STK", "STK-Enhanced"],
	},
	ACS12: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: ["Muzzle Brake", "Standard Muzzle"],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"RU Collimator Sight",
			"RU Red Dot Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
		],
	},
	AK12: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"RU Collimator Sight",
			"RU Red Dot G33 Sight",
			"RU Red Dot Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
	},
	AK47: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"762 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"RU Collimator Sight",
			"RU Red Dot G33 Sight",
			"RU Red Dot Sight",
			"TA31H Sight",
		],
		rail: ["PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: ["Underbarrel Grenade Launcher", "Underbarrel Rail (None)"],
		stock: [
			"Short Barrel",
			"OCTOB-STK",
			"PT1",
			"STK-P",
			"STK-W",
			"Zhukov Stock",
			"Core CP",
		],
	},
	AK74: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"RU Collimator Sight",
			"RU Red Dot G33 Sight",
			"RU Red Dot Sight",
			"TA31H Sight",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: ["Underbarrel Grenade Launcher", "Underbarrel Rail (None)"],
		stock: [
			"Short Barrel",
			"OCTOB-STK",
			"PT1",
			"STK-P",
			"STK-W",
			"Zhukov Stock",
			"Core CP",
		],
	},
	"AK74 Scout": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Ironsight",
			"Dual Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: ["OCTOB-STK", "PT1", "STK-P", "STK-W", "Zhukov Stock", "Core CP"],
	},
	"AR-18": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
		],
	},
	ARX200: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"762 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3",
			"MICROT1XG33 Sight",
			"MICROT1 Sight",
			"SLX5 Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: ["Adjustable Stock"],
	},
	AUG: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"RU Red Dot G33 Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	"Aug Scout": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"RU Long-Range Sight",
			"SLX5 Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
		],
	},
	BOSG12: {},
	"Bailiff 410": {},
	"Bullpup PDR": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"Digital Sight",
			"EXPS3",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
			"RU Collimator Sight",
			"SLX5 Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
	},
	"C-SFP": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Ripples Silencer",
		],
		magazine: ["Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	CTMMG: {
		muzzle: ["Compensator", "Flash Hider", "Muzzle Brake", "Standard Muzzle"],
		magazine: ["Standard Magazine"],
		scope: [
			"Ironsight",
			"EXPS3",
			"MICROT1 Sight",
			"Panoramic Sight",
			"RU Red Dot Sight",
			"SLX5 Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: ["Grip Pod", "Tactical Vertical Foregrip"],
	},
	"Desert Eagle": {
		magazine: ["Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	"Echelon SMG": {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Kilim Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
			"SLX5 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: ["Adjustable Stock"],
	},
	F40: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Ripples Silencer",
		],
		magazine: ["Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	FAL: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"762 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
	},
	FRF2: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Dual Range Sight",
			"RU Long-Range FOV Sight",
			"RU Long-Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TARS101",
			"VC16 Sight",
		],
	},
	G2: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3",
			"MICROT1XG33 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	G28: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Digital Sight",
			"Dual Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: ["Adjustable Stock"],
	},
	G36C: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
		stock: ["STK-KV", "STK-P", "Convex Stock"],
	},
	"G36C Scout": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Ironsight",
			"Digital Sight",
			"Dual Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: ["STK-KV", "STK-P", "Convex Stock"],
	},
	HTI: {
		muzzle: [
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"338 Control Shield",
		],
		magazine: ["Standard Magazine"],
		scope: [
			"Digital Sight",
			"Dual Range Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		underbarrel: ["Bipod", "Underbarrel Rail (None)"],
	},
	"Honey Badger": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Suppressor",
			"556 Control Shield",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"Digital Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
			"SLX5 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
		],
		stock: ["Adjustable Stock"],
	},
	K1A: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
			"SLX5 Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
	},
	KSG12: {
		muzzle: ["Muzzle Brake", "Standard Muzzle"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},

	L115A3: {
		muzzle: [
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"338 Control Shield",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Digital Sight",
			"Dual Range Sight",
			"RU Long-Range FOV Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
	},
	"L85-C": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"SLX5 Sight",
			"T5XI Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
		],
	},
	L86A1: {
		muzzle: ["Compensator", "Flash Hider", "Muzzle Brake", "Standard Muzzle"],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"EXPS3",
			"MICROT1 Sight",
			"RU Collimator Sight",
			"RU Red Dot G33 Sight",
			"RU Red Dot Sight",
			"SLX5 Sight",
			"TA31H Sight",
		],
		underbarrel: ["Bipod", "Grip Pod", "Rounded Angled Foregrip"],
	},
	M110: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Ironsight",
			"Digital Sight",
			"Dual Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: [
			"A2-M",
			"ARM",
			"CTR",
			"Core CP",
			"DD-CB",
			"E1",
			"EMOD",
			"HMM",
			"KAC-SASS",
			"M4",
			"MS-U",
			"UBR Gen2",
		],
	},
	M1911: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Ripples Silencer",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	M4: {
		muzzle: ["Muzzle Brake", "Standard Muzzle", "Suppressor"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
		],
		stock: ["Breacher", "STK-H20", "UBO"],
	},
	M4A1: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: [
			"Extended Magazine",
			"Small Magazine",
			"Standard Magazine",
			"ASR 100 Rounds Magazine",
		],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
		stock: [
			"A2-M",
			"ARM",
			"CTR",
			"CTR-SLK",
			"Core CP",
			"DD-CB",
			"E1",
			"EMOD",
			"HMM",
			"IMOD",
			"M-BRS",
			"M4",
			"MS-U",
			"Mini-CQB",
			"Socom-1",
			"TACLite",
			"UBR Gen2",
		],
	},
	"M4A1 Scout": {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Dual Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["MAWL-DA", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: [
			"A2-M",
			"ARM",
			"CTR",
			"CTR-SLK",
			"Core CP",
			"DD-CB",
			"E1",
			"EMOD",
			"HMM",
			"IMOD",
			"M-BRS",
			"M4",
			"MS-U",
			"Mini-CQB",
			"Socom-1",
			"TACLite",
			"UBR Gen2",
		],
	},
	M590A1: {
		muzzle: ["Muzzle Brake", "Standard Muzzle", "Suppressor"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	M82: {
		muzzle: [
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"338 Control Shield",
		],
		magazine: ["Standard Magazine"],
		scope: [
			"Digital Sight",
			"Dual Range Sight",
			"RU Long-Range Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
	},
	M9: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Ripples Silencer",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	MDR: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"762 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	MG121: {
		muzzle: ["Compensator", "Flash Hider", "Muzzle Brake", "Standard Muzzle"],
		magazine: ["Standard Magazine"],
		scope: [
			"Ironsight",
			"RU Collimator Sight",
			"RU Red Dot G33 Sight",
			"RU Red Dot Sight",
			"SLX5 Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: ["Bipod", "Grip Pod", "RU Vertical Foregrip"],
	},
	MGL: {},
	MK14: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"Digital Sight",
			"Dual Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: ["Adjustable Stock"],
	},
	MK17: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"762 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
		stock: ["Short Barrel", "Mini-SC", "STK", "STK-Enhanced"],
	},
	"MK17 Scout": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Ironsight",
			"Dual Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	MK18: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Underbarrel Shotgun",
			"Vented Angled Foregrip",
		],
		stock: [
			"A2-M",
			"ARM",
			"CTR",
			"CTR-SLK",
			"Core CP",
			"DD-CB",
			"E1",
			"EMOD",
			"HMM",
			"IMOD",
			"KAC-SASS",
			"M-BRS",
			"M4",
			"MS-U",
			"Mini-CQB",
			"Socom-1",
			"TACLite",
			"UBR Gen2",
		],
	},
	MK23: {
		muzzle: ["Compensator", "Flash Hider", "Muzzle Brake", "Suppressor"],
		magazine: ["Standard Magazine"],
	},
	MK48: {
		muzzle: ["Compensator", "Flash Hider", "Muzzle Brake", "Standard Muzzle"],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"MICROT1 Sight",
			"Panoramic Sight",
			"RU Red Dot Sight",
			"SLX5 Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: ["Bipod", "Grip Pod", "Tactical Vertical Foregrip"],
	},
	MP5: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Kilim Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
			"SLX5 Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: ["Adjustable Stock"],
	},
	MP7: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Kilim Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover"],
		stock: ["Adjustable Stock"],
	},
	MPX: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Kilim Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
			"SLX5 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
		],
		stock: ["Adjustable Stock"],
	},
	MSR: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"338 Control Shield",
		],
		magazine: ["Standard Magazine"],
		scope: [
			"Digital Sight",
			"Dual Range Sight",
			"RU Long-Range FOV Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: ["Bipod", "Underbarrel Rail (None)"],
	},
	"Maxim 9": {
		muzzle: ["Suppressor"],
		magazine: ["Standard Magazine"],
	},
	"OTS-03": {
		muzzle: ["Suppressor"],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Digital Sight",
			"Dual Range Sight",
			"RU Long-Range FOV Sight",
			"RU Long-Range Sight",
			"RU Red Dot G33 Sight",
			"TARS101",
		],
		underbarrel: [
			"Bipod",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
		],
	},
	P227: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Ripples Silencer",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	P320: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Ripples Silencer",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	P45T: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Ripples Silencer",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	P90: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Kilim Silencer",
		],
		magazine: ["Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
	},
	PX4: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Ripples Silencer",
		],
		magazine: ["Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	"Paladin 9 SNR": {
		muzzle: ["Suppressor"],
		magazine: ["Standard Magazine"],
		scope: [
			"Dual Range Sight",
			"Paladin Optic",
			"RU Long-Range FOV Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: ["Bipod", "RVG Vertical Foregrip", "Underbarrel Rail (None)"],
	},
	RU12SG: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: ["Muzzle Brake", "Standard Muzzle", "Suppressor"],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"RU Collimator Sight",
			"RU Red Dot Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: ["OCTOB-STK", "PT1", "STK-P", "STK-W", "Zhukov Stock", "Core CP"],
	},
	"Recon-A1": {
		muzzle: [
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"338 Control Shield",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Digital Sight",
			"Dual Range Sight",
			"T5XI Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: ["Bipod", "RVG Vertical Foregrip", "Underbarrel Rail (None)"],
	},
	"Resistance ASR": {
		magazine: ["Small Magazine", "Standard Magazine"],
	},
	SASG12: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: ["Muzzle Brake", "Standard Muzzle", "Suppressor"],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"RU Collimator Sight",
			"RU Red Dot Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
		stock: ["OCTOB-STK", "PT1", "STK-P", "STK-W", "Zhukov Stock", "Core CP"],
	},
	"SC IS HDG": {
		muzzle: ["Suppressor"],
		magazine: ["Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	"SC-20K": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"MICROT1 Sight",
			"RU Long-Range FOV Sight",
			"RU Red Dot G33 Sight",
			"TA31H Sight",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
	},
	"SC-40K": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3",
			"MH1 Sight",
			"Panoramic Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	"SN-9mm": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Kilim Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
			"SLX5 Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	"SPAS-12": {
		muzzle: ["Muzzle Brake", "Standard Muzzle"],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
		],
	},
	"SR-1": {
		muzzle: [
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"338 Control Shield",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Digital Sight",
			"Dual Range Sight",
			"T5XI Sight",
			"TARS101",
			"VC16 Sight",
		],
	},
	"SR-3M": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"762 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"Digital Sight",
			"Panoramic Sight",
			"RU Collimator Sight",
			"RU Long-Range FOV Sight",
			"RU Long-Range Sight",
			"RU Red Dot G33 Sight",
			"RU Red Dot Sight",
		],
		rail: ["PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: ["Underbarrel Grenade Launcher"],
		stock: ["OCTOB-STK", "STK-P", "STK-W"],
	},
	"SR-3M Scout": {
		muzzle: ["Suppressor"],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"Digital Sight",
			"RU Collimator Sight",
			"RU Long-Range FOV Sight",
			"RU Long-Range Sight",
			"RU Red Dot G33 Sight",
			"T5XI Sight",
			"VC16 Sight",
		],
		rail: ["PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
		],
		stock: ["OCTOB-STK", "STK-P", "STK-W"],
	},
	"SVD-63": {
		muzzle: ["Muzzle Brake", "Standard Muzzle", "Suppressor"],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Digital Sight",
			"Dual Range Sight",
			"RU Long-Range Sight",
			"SLX5 Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["PEQ-15", "Rail Cover", "Range Finder"],
	},
	Scorpio: {
		muzzle: [
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"338 Control Shield",
		],
		magazine: ["Standard Magazine"],
		scope: [
			"Digital Sight",
			"Dual Range Sight",
			"RU Long-Range FOV Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		underbarrel: ["Bipod", "Underbarrel Rail (None)"],
	},
	"Scorpio Scout": {
		muzzle: ["Muzzle Brake", "Standard Muzzle", "Suppressor"],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Digital Sight",
			"Dual Range Sight",
			"RU Long-Range FOV Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		underbarrel: ["Bipod", "Underbarrel Rail (None)"],
	},
	"Scorpion EVO3": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
			"SLX5 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	"Sharp Thunder": {},
	"Silver Stake": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"COMPM4 Sight",
			"Digital Sight",
			"Dual Range Sight",
			"EXPS3XG33 Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"Rounded Angled Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	"Stainless Extended .45": {
		muzzle: ["Standard Muzzle", "Suppressor", "Ripples Silencer"],
		magazine: ["Standard Magazine"],
	},
	Stoner: {
		muzzle: ["Compensator", "Flash Hider", "Muzzle Brake", "Standard Muzzle"],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"EXPS3",
			"MICROT1 Sight",
			"Panoramic Sight",
			"RU Red Dot Sight",
			"SLX5 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover"],
		underbarrel: ["Bipod", "Grip Pod", "RVG Vertical Foregrip"],
	},
	T95: {
		muzzle: ["Compensator", "Flash Hider", "Muzzle Brake", "Standard Muzzle"],
		magazine: ["Standard Magazine"],
		scope: [
			"Ironsight",
			"EXPS3",
			"MICROT1 Sight",
			"Panoramic Sight",
			"RU Red Dot Sight",
			"SLX5 Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
	},
	Tac50: {
		muzzle: [
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"338 Control Shield",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		scope: [
			"Digital Sight",
			"Dual Range Sight",
			"RU Long-Range Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		underbarrel: ["Bipod", "Underbarrel Rail (None)"],
	},
	Tavor: {
		barrel: ["Standard Barrel", "Short Barrel"],
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
		],
	},
	"Tavor Scout": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
		],
		magazine: ["Small Magazine", "Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Ironsight",
			"Dual Range Sight",
			"SLX5 Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	UMP: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Kilim Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1XG33 Sight",
			"MICROT1 Sight",
			"RU Collimator Sight",
			"SLX5 Sight",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
		],
	},
	"USP Tactical": {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Ripples Silencer",
		],
		magazine: ["Extended Magazine", "Standard Magazine"],
		rail: ["ATPIALx3", "Rail Cover", "ATPIAL HDG Laser"],
	},
	"Uzi 9mm": {
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
		],
		stock: ["Adjustable Stock"],
	},
	VHSD2: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"556 Control Shield",
			"Hive Silencer",
			"Prism Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3XG33 Sight",
			"EXPS3",
			"Panoramic Sight",
			"TA31H Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Grenade Launcher",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	"VSK-50": {
		muzzle: ["Muzzle Brake", "Suppressor"],
		magazine: ["Standard Magazine"],
		scope: [
			"ACSS Sight",
			"Ironsight",
			"Digital Sight",
			"Dual Range Sight",
			"RU Long-Range FOV Sight",
			"RU Long-Range Sight",
			"RU Red Dot G33 Sight",
			"TARS101",
		],
		rail: ["ATPIALx3", "PEQ-15", "Rail Cover", "Range Finder"],
		underbarrel: [
			"AFG-2 Angled Foregrip",
			"Bipod",
			"Bipod and Foregrip Combo",
			"Grip Pod",
			"Lightweight Vertical Foregrip",
			"PTK Angled Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"STFG Angled Grip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
			"Vented Angled Foregrip",
		],
	},
	Vector: {
		muzzle: [
			"Compensator",
			"Flash Hider",
			"Muzzle Brake",
			"Standard Muzzle",
			"Suppressor",
			"Kilim Silencer",
		],
		magazine: ["Extended Magazine", "Small Magazine", "Standard Magazine"],
		scope: [
			"Ironsight",
			"COMPM4 Sight",
			"Digital Sight",
			"EXPS3",
			"LEUPOLD Holo Sight",
			"MH1 Sight",
			"MICROT1 Sight",
			"Panoramic Sight",
		],
		rail: ["ATPIALx3", "MAWL-DA", "PEQ-15", "Rail Cover"],
		underbarrel: [
			"Lightweight Vertical Foregrip",
			"RU Vertical Foregrip",
			"RVG Vertical Foregrip",
			"SHIFT Angled Short Grip",
			"SHIFT Vertical Foregrip",
			"Tactical Vertical Foregrip",
			"Underbarrel Rail (None)",
		],
	},
	"Zastava M93": {
		magazine: ["Standard Magazine"],
		scope: [
			"RU Long-Range FOV Sight",
			"RU Long-Range Sight",
			"T5XI Sight",
			"TA31H Sight",
			"TARS101",
			"VC16 Sight",
		],
	},
};

// Helper: get all weapons flat (useful for search/validation)
export const ALL_WEAPONS = Object.values(WEAPONS_BY_TYPE).flat();

// Helper: lookup weapon type from weapon name
export const getWeaponType = (weaponName) => {
	for (const [type, weapons] of Object.entries(WEAPONS_BY_TYPE)) {
		if (weapons.includes(weaponName)) return type;
	}
	return null;
};

// Helper: get compatible attachments for a weapon, optionally filtered by slot.
// Returns the full slot map if no slot is specified, or the array for that slot.
// Returns [] (or {}) if the weapon is unknown or has no attachments for that slot.
export const getCompatibleAttachments = (weaponName, slot = null) => {
	const compat = WEAPON_COMPATIBILITY[weaponName];
	if (!compat) return slot ? [] : {};
	if (slot) return compat[slot] || [];
	return compat;
};

// Helper: check whether a specific attachment is compatible with a weapon.
// Useful for form validation when a player switches weapons mid-build.
export const isCompatible = (weaponName, slot, attachment) => {
	const slotAttachments = getCompatibleAttachments(weaponName, slot);
	return slotAttachments.includes(attachment);
};
