// ─────────────────────────────────────────────────────────────────────────────
// MissionGenerator.jsx
// Province → locations → mission type → Generate.
// Points placed by GeneratePoints.js (algorithmic).
// Briefing generated by BriefingGenerator.js (pure function).
// Zero AI calls in this flow.
// ─────────────────────────────────────────────────────────────────────────────

import { useState, useEffect } from "react";
import PropTypes from "prop-types";
import { toast } from "react-toastify";
import { PROVINCES, PROVINCE_TERRAIN } from "@/config";
import { MISSION_TYPES, MISSION_CATEGORIES } from "@/api/GhostOpsApi";
import { generatePoints } from "@/utils/GeneratePoints";
import { generateBriefing } from "@/utils/BriefingGenerator";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
	faLocationDot,
	faShuffle,
	faListCheck,
	faBolt,
	faSpinner,
	faMinus,
	faPlus,
	faCrosshairs,
	faSkull,
	faBomb,
	faHandcuffs,
	faTruck,
	faEye,
	faUserSecret,
	faHandsBound,
} from "@fortawesome/free-solid-svg-icons";

// ── FA icon map ───────────────────────────────────────────────────────────────

const ICON_MAP = {
	faCrosshairs,
	faSkull,
	faBomb,
	faHandcuffs,
	faTruck,
	faEye,
	faUserSecret,
	faHandsBound,
	faBolt,
	faListCheck,
	faShuffle,
};

const resolveIcon = (key) => ICON_MAP[key] ?? faCrosshairs;

// ── Category accent colours ───────────────────────────────────────────────────

const CATEGORY_STYLES = {
	"Direct Action": { header: "text-red-400/50", divider: "bg-red-400/10" },
	"Special Reconnaissance": {
		header: "text-indigo-400/50",
		divider: "bg-indigo-400/10",
	},
	Counterterrorism: { header: "text-cyan-400/50", divider: "bg-cyan-400/10" },
	Overwatch: { header: "text-emerald-400/50", divider: "bg-emerald-400/10" },
	Support: { header: "text-emerald-400/50", divider: "bg-emerald-400/10" },
};

// ─── Sub-components ───────────────────────────────────────────────────────────

function HudSelect({ label, value, onChange, children }) {
	return (
		<div className='flex flex-col gap-1'>
			<span className='font-mono text-[9px] tracking-[0.22em] text-lines/40 uppercase'>
				{label}
			</span>
			<div className='relative'>
				<select
					value={value}
					onChange={onChange}
					className='w-full appearance-none bg-blk/60 border border-lines/25 hover:border-lines/50 focus:border-btn/60 focus:outline-none rounded-sm px-3 py-2 font-mono text-[11px] text-fontz/80 cursor-pointer transition-colors'>
					{children}
				</select>
				<div className='absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none'>
					<div className='w-0 h-0 border-l-[4px] border-r-[4px] border-t-[5px] border-l-transparent border-r-transparent border-t-lines/30' />
				</div>
			</div>
		</div>
	);
}

function ActionBtn({
	onClick,
	disabled,
	loading,
	icon,
	label,
	variant = "default",
	wide = false,
}) {
	const variants = {
		default:
			"text-btn border-btn/35 bg-btn/8 hover:bg-btn/18 hover:border-btn/60",
		primary: "text-blk border-btn bg-btn hover:bg-highlight",
		muted: "text-lines/20 border-lines/10 bg-transparent cursor-not-allowed",
	};
	return (
		<button
			onClick={onClick}
			disabled={disabled || loading}
			className={[
				"flex items-center justify-center gap-2 border rounded-sm font-mono text-[10px] tracking-widest uppercase transition-all py-2",
				wide ? "w-full px-4" : "px-3",
				disabled || loading ? variants.muted : variants[variant],
			].join(" ")}>
			{loading ?
				<FontAwesomeIcon
					icon={faSpinner}
					className='animate-spin text-[10px]'
				/>
			:	icon && (
					<FontAwesomeIcon
						icon={icon}
						className='text-[10px]'
					/>
				)
			}
			{label}
		</button>
	);
}

// ── Mission type grid ─────────────────────────────────────────────────────────

function MissionTypeGrid({ value, onChange }) {
	const grouped = MISSION_CATEGORIES.map((cat) => ({
		category: cat,
		missions: MISSION_TYPES.filter((m) => m.category === cat),
	})).filter((g) => g.missions.length > 0);

	const selected = MISSION_TYPES.find((m) => m.id === value);

	return (
		<div className='flex flex-col gap-2'>
			<div className='flex items-center gap-2'>
				<span className='font-mono text-[9px] tracking-[0.22em] text-lines/40 uppercase'>
					Mission Type
				</span>
				<div className='flex-1 h-px bg-lines/10' />
			</div>

			{grouped.map(({ category, missions }) => {
				const catStyle = CATEGORY_STYLES[category] ?? {
					header: "text-lines/40",
					divider: "bg-lines/10",
				};
				return (
					<div
						key={category}
						className='flex flex-col gap-1'>
						<div className='flex items-center gap-1.5'>
							<span
								className={`font-mono text-[7px] tracking-[0.25em] uppercase ${catStyle.header}`}>
								{category}
							</span>
							<div className={`flex-1 h-px ${catStyle.divider}`} />
						</div>
						<div className='grid grid-cols-4 gap-1'>
							{missions.map((t) => {
								const active = value === t.id;
								return (
									<button
										key={t.id}
										onClick={() => onChange(active ? "" : t.id)}
										title={t.fullLabel ?? t.label}
										className={[
											"flex flex-col items-center gap-1 py-2 px-1 border rounded-sm transition-all",
											active ?
												`${t.activeBorder} ${t.activeBg}`
											:	"border-lines/15 hover:border-lines/30",
										].join(" ")}>
										<FontAwesomeIcon
											icon={resolveIcon(t.icon)}
											className={`text-[11px] ${active ? t.color : "text-lines/25"}`}
										/>
										<span
											className={`font-mono text-[8px] tracking-widest ${active ? t.color : "text-lines/30"}`}>
											{t.abbr}
										</span>
									</button>
								);
							})}
						</div>
					</div>
				);
			})}

			{selected && (
				<span className='font-mono text-[8px] text-lines/40 italic'>
					{selected.fullLabel ?? selected.label}
				</span>
			)}
		</div>
	);
}

// ═══════════════════════════════════════════════════════════════
// MISSION GENERATOR
// ═══════════════════════════════════════════════════════════════

export default function MissionGenerator({
	onGenerateRandomOps,
	onGenerateOps,
	setMapBounds,
	setImgURL,
	generationMode,
	setGenerationMode,
	priorPhases = [],
}) {
	const [selectedProvince, setSelectedProvince] = useState("");
	const [selectedLocations, setSelectedLocations] = useState([]);
	const [numberOfLocations, setNumberOfLocations] = useState(1);
	const [missionType, setMissionType] = useState("");
	const [loading, setLoading] = useState(false);

	const provinces = Object.keys(PROVINCES);
	const locationsInProvince =
		selectedProvince ? PROVINCES[selectedProvince].locations : [];

	// Reset on mode or province change
	useEffect(() => {
		setSelectedLocations([]);
		setMissionType("");
		setMapBounds(null);
		setImgURL("");
	}, [generationMode, selectedProvince]);

	// ── Resolve locations for current mode ───────────────────────────────────
	const resolveLocations = () => {
		const pd = PROVINCES[selectedProvince];
		if (generationMode === "random") {
			const shuffled = [...pd.locations].sort(() => Math.random() - 0.5);
			return shuffled.slice(0, Math.min(numberOfLocations, shuffled.length));
		}
		return selectedLocations
			.map((n) => pd.locations.find((l) => l.name === n))
			.filter(Boolean);
	};

	// ── Main generate handler ─────────────────────────────────────────────────
	const handleGenerate = async () => {
		if (!selectedProvince) {
			toast.warn("Select a province.");
			return;
		}
		if (generationMode === "ops" && selectedLocations.length === 0) {
			toast.error("Select at least one location.");
			return;
		}
		if (!missionType) {
			toast.warn("Select a mission type.");
			return;
		}

		setLoading(true);

		try {
			const pd = PROVINCES[selectedProvince];
			const terrain = PROVINCE_TERRAIN?.[selectedProvince] ?? null;
			const locations = resolveLocations();

			if (!locations.length) {
				toast.error("No valid locations resolved.");
				return;
			}

			// ── 1. Generate points algorithmically ───────────────────────────────
			const points = generatePoints({
				missionType,
				terrain,
				objectives: locations,
			});

			// ── 2. Generate briefing from config data ────────────────────────────
			const briefing = generateBriefing({
				operationName: "", // filled by parent from mission.name
				province: selectedProvince,
				biome: pd.biome,
				missionType,
				locations,
				generator: points,
				priorPhases,
			});

			// ── 3. Build payload and call parent ─────────────────────────────────
			const payload = {
				selectedProvince,
				biome: pd.biome,
				bounds: pd.coordinates.bounds,
				imgURL: pd.imgURL,
				randomSelection: locations,
				missionType,
				// Points from GeneratePoints
				infilPoint: points.infilPoint,
				exfilPoint: points.exfilPoint,
				rallyPoint: points.rallyPoint,
				infilMethod: points.infilMethod,
				exfilMethod: points.exfilMethod,
				approachVector: points.approachVector,
				// Briefing from BriefingGenerator
				briefing,
			};

			if (generationMode === "random") {
				onGenerateRandomOps(payload);
			} else {
				onGenerateOps(payload);
			}

			// Live map preview
			setMapBounds(pd.coordinates.bounds);
			setImgURL(pd.imgURL);
		} catch (err) {
			console.error(err);
			toast.error(err.message || "Generation failed.");
		} finally {
			setLoading(false);
		}
	};

	// ── Render ────────────────────────────────────────────────────────────────
	return (
		<div className='flex flex-col gap-4 h-full'>
			{/* Mode toggle */}
			<div className='flex gap-0 border border-lines/20 rounded-sm overflow-hidden shrink-0'>
				{[
					{ id: "random", icon: faShuffle, label: "Random" },
					{ id: "ops", icon: faListCheck, label: "Mission" },
				].map((m) => {
					const active = generationMode === m.id;
					return (
						<button
							key={m.id}
							onClick={() => setGenerationMode(m.id)}
							className={[
								"flex-1 flex items-center justify-center gap-2 py-2 font-mono text-[10px] tracking-widest uppercase transition-all",
								active ? "bg-btn/20 text-btn" : (
									"text-lines/35 hover:text-fontz hover:bg-white/[0.03]"
								),
							].join(" ")}>
							<FontAwesomeIcon
								icon={m.icon}
								className='text-[9px]'
							/>
							{m.label}
						</button>
					);
				})}
			</div>

			{/* Scrollable form body */}
			<div className='flex flex-col gap-3 flex-1 min-h-0 overflow-y-auto'>
				{/* Province */}
				<HudSelect
					label='Province'
					value={selectedProvince}
					onChange={(e) => {
						setSelectedProvince(e.target.value);
						setSelectedLocations([]);
					}}>
					<option value=''>— Select Province —</option>
					{provinces.map((p) => (
						<option
							key={p}
							value={p}>
							{p}
						</option>
					))}
				</HudSelect>

				{/* Random mode — location count stepper */}
				{generationMode === "random" && selectedProvince && (
					<div className='flex flex-col gap-1'>
						<span className='font-mono text-[9px] tracking-[0.22em] text-lines/40 uppercase'>
							Locations
						</span>
						<div className='flex items-center gap-0 border border-lines/25 rounded-sm overflow-hidden w-32'>
							<button
								onClick={() => setNumberOfLocations((n) => Math.max(1, n - 1))}
								className='w-9 h-9 flex items-center justify-center text-lines/40 hover:text-btn hover:bg-btn/10 transition-colors border-r border-lines/20'>
								<FontAwesomeIcon
									icon={faMinus}
									className='text-[9px]'
								/>
							</button>
							<span className='flex-1 text-center font-mono text-xs text-fontz tabular-nums'>
								{numberOfLocations}
							</span>
							<button
								onClick={() => setNumberOfLocations((n) => n + 1)}
								className='w-9 h-9 flex items-center justify-center text-lines/40 hover:text-btn hover:bg-btn/10 transition-colors border-l border-lines/20'>
								<FontAwesomeIcon
									icon={faPlus}
									className='text-[9px]'
								/>
							</button>
						</div>
					</div>
				)}

				{/* Ops mode — location checklist */}
				{generationMode === "ops" &&
					selectedProvince &&
					locationsInProvince.length > 0 && (
						<div className='flex flex-col gap-1'>
							<span className='font-mono text-[9px] tracking-[0.22em] text-lines/40 uppercase'>
								Locations{" "}
								<span className='text-btn ml-1'>
									{selectedLocations.length} selected
								</span>
							</span>
							<div className='flex flex-col gap-0.5 max-h-36 overflow-y-auto border border-lines/15 rounded-sm bg-blk/40 p-1'>
								{locationsInProvince.map((loc) => {
									const checked = selectedLocations.includes(loc.name);
									return (
										<label
											key={loc.name}
											className={[
												"flex items-center gap-2.5 px-2.5 py-1.5 rounded-sm cursor-pointer transition-colors",
												checked ?
													"bg-btn/10 border border-btn/20"
												:	"hover:bg-white/[0.03] border border-transparent",
											].join(" ")}>
											<span
												className={[
													"w-3 h-3 border rounded-sm shrink-0 flex items-center justify-center transition-colors",
													checked ? "bg-btn border-btn" : (
														"border-lines/30 bg-transparent"
													),
												].join(" ")}>
												{checked && (
													<span className='w-1.5 h-1 border-b border-r border-blk rotate-45 -translate-y-px' />
												)}
											</span>
											<input
												type='checkbox'
												className='sr-only'
												value={loc.name}
												checked={checked}
												onChange={(e) =>
													setSelectedLocations(
														e.target.checked ?
															[...selectedLocations, loc.name]
														:	selectedLocations.filter((l) => l !== loc.name),
													)
												}
											/>
											<span className='font-mono text-[10px] text-fontz/70'>
												<FontAwesomeIcon
													icon={faLocationDot}
													className='text-lines/25 mr-1.5 text-[8px]'
												/>
												{loc.name}
											</span>
										</label>
									);
								})}
							</div>
						</div>
					)}

				{/* Mission type grid */}
				{selectedProvince && (
					<MissionTypeGrid
						value={missionType}
						onChange={setMissionType}
					/>
				)}
			</div>

			{/* Generate button */}
			<div className='shrink-0'>
				<ActionBtn
					onClick={handleGenerate}
					loading={loading}
					disabled={!selectedProvince || !missionType}
					icon={faBolt}
					label='Generate'
					variant='primary'
					wide
				/>
			</div>
		</div>
	);
}

// ─── PropTypes ────────────────────────────────────────────────────────────────

MissionGenerator.propTypes = {
	onGenerateRandomOps: PropTypes.func.isRequired,
	onGenerateOps: PropTypes.func.isRequired,
	setMapBounds: PropTypes.func.isRequired,
	setImgURL: PropTypes.func.isRequired,
	generationMode: PropTypes.string.isRequired,
	setGenerationMode: PropTypes.func.isRequired,
	priorPhases: PropTypes.array,
};

HudSelect.propTypes = {
	label: PropTypes.string,
	value: PropTypes.string,
	onChange: PropTypes.func,
	children: PropTypes.node,
};

ActionBtn.propTypes = {
	onClick: PropTypes.func,
	disabled: PropTypes.bool,
	loading: PropTypes.bool,
	icon: PropTypes.object,
	label: PropTypes.string,
	variant: PropTypes.string,
	wide: PropTypes.bool,
};

MissionTypeGrid.propTypes = {
	value: PropTypes.string,
	onChange: PropTypes.func.isRequired,
};
